import { beforeEach, describe, expect, it, vi } from 'vitest'
import { createReferenceLibraryController } from '../../packages/editor-vue/src/services/referenceLibrary'
import { createLocalReferenceServices, emptyReferenceLibrary, type ReferenceLibrary } from '../../packages/editor-vue/src/services/referenceEditorServices'
const ref = { id: 'r1', number: 9, text: 'First' }
describe('private reference library controller', () => {
  beforeEach(() => localStorage.clear())
  it('captures cold references before awaiting load and retains the last removed citation on reload', async () => {
    let resolve!: (value: ReferenceLibrary) => void
    const service = createLocalReferenceServices(localStorage)
    const controller = createReferenceLibraryController({ ...service, loadLibrary: () => new Promise(done => { resolve = done }) }, localStorage)
    const loading = controller.load('a')
    controller.observe('a', [ref])
    controller.observe('a', [])
    expect(localStorage.getItem('w-editor:reference-library-pending:v1:a')).toContain('First')
    resolve(emptyReferenceLibrary())
    await loading
    await controller.flush('a')
    controller.dispose()
    const reopened = createReferenceLibraryController(service, localStorage)
    expect(await reopened.load('a')).toMatchObject({ entries: [{ id: 'r1', text: 'First' }], highWater: 9 })
    reopened.dispose()
  })
  it('ignores initial stale body metadata and tombstones, but captures subsequent undo edits', async () => {
    const service = createLocalReferenceServices(localStorage)
    await service.saveLibrary!('a', { revision: 0, entries: [{ id: 'r1', text: 'Remote' }], deletedIds: ['r2'], highWater: 8 })
    const c = createReferenceLibraryController(service, localStorage)
    const loading = c.load('a')
    c.observe('a', [ref, { id: 'r2', text: 'Deleted', number: 10 }])
    await loading
    expect(c.get('a').entries).toEqual([{ id: 'r1', text: 'Remote' }])
    c.observe('a', [{ ...ref, text: 'Edited body' }])
    await c.flush('a')
    expect(c.get('a').entries[0]?.text).toBe('Edited body')
    c.dispose()
  })
  it('preserves failed mutations for recovery and merges disjoint CAS conflicts on retry', async () => {
    const service = createLocalReferenceServices(localStorage)
    const c = createReferenceLibraryController(service, localStorage)
    await c.load('a')
    await service.saveLibrary!('a', { ...emptyReferenceLibrary(), entries: [{ id: 'remote', text: 'Remote' }] })
    await expect(c.collect('a', { id: 'local', text: 'Local' })).rejects.toThrow('修改')
    expect(localStorage.getItem('w-editor:reference-library-pending:v1:a')).toContain('Local')
    c.dispose()
    const reopened = createReferenceLibraryController(service, localStorage)
    await reopened.retry('a')
    expect(reopened.get('a').entries.map(entry => entry.id)).toEqual(['remote', 'local'])
    reopened.dispose()
  })
  it('rejects overlapping conflicts repeatedly without losing local recovery', async () => {
    const service = createLocalReferenceServices(localStorage)
    const c = createReferenceLibraryController(service, localStorage)
    await c.collect('a', { id: 'r1', text: 'Base' })
    await service.saveLibrary!('a', { ...c.get('a'), entries: [{ id: 'r1', text: 'Other editor' }] })
    await expect(c.update('a', { id: 'r1', text: 'Mine' })).rejects.toThrow()
    await expect(c.retry('a')).rejects.toThrow('同一文献')
    expect(c.get('a').entries[0]?.text).toBe('Mine')
    expect(localStorage.getItem('w-editor:reference-library-pending:v1:a')).toContain('Mine')
    c.dispose()
  })
  it('isolates delayed documents, avoids unchanged writes, and requires explicit revival', async () => {
    const service = createLocalReferenceServices(localStorage)
    const save = vi.fn(service.saveLibrary!)
    const c = createReferenceLibraryController({ ...service, saveLibrary: save }, localStorage)
    c.observe('a', [ref])
    c.observe('b', [{ ...ref, id: 'b', text: 'Second' }])
    await Promise.all([c.flush('a'), c.flush('b')])
    const count = save.mock.calls.length
    c.observe('a', [ref])
    await c.flush('a')
    expect(save).toHaveBeenCalledTimes(count)
    await c.remove('a', ref.id)
    c.observe('a', [ref])
    await c.flush('a')
    expect(c.get('a').entries).toEqual([])
    expect(c.get('b').entries[0]?.id).toBe('b')
    await c.collect('a', ref)
    expect(c.get('a').deletedIds).toEqual([])
    expect(c.get('a').entries[0]).not.toHaveProperty('number')
    c.dispose()
  })
  it('retains collection input even when the first remote load fails', async () => {
    const service = createLocalReferenceServices(localStorage)
    const c = createReferenceLibraryController({ ...service, loadLibrary: async () => { throw new Error('Offline') } }, localStorage)
    await expect(c.collect('offline', { id: 'one', text: 'Recover me' })).rejects.toThrow('Offline')
    expect(localStorage.getItem('w-editor:reference-library-pending:v1:offline')).toContain('Recover me')
    c.dispose()
    const reopened = createReferenceLibraryController(service, localStorage)
    await reopened.retry('offline')
    expect(reopened.get('offline').entries[0]?.text).toBe('Recover me')
    reopened.dispose()
  })
  it('clears failure notices only after a successful flush', async () => {
    const service = createLocalReferenceServices(localStorage)
    const notice = vi.fn()
    const c = createReferenceLibraryController(service, localStorage, undefined, notice)
    c.observe('doc', [ref])
    await c.load('doc')
    expect(notice).not.toHaveBeenCalledWith('doc', '')
    await c.flush('doc')
    expect(notice).toHaveBeenLastCalledWith('doc', '')
    c.dispose()
  })
  it('surfaces malformed recovery without crashing observation or overwriting evidence', async () => {
    const key = 'w-editor:reference-library-pending:v1:doc'
    localStorage.setItem(key, '{damaged')
    const notice = vi.fn()
    const c = createReferenceLibraryController(createLocalReferenceServices(localStorage), localStorage, undefined, notice)
    expect(() => c.observe('doc', [ref])).not.toThrow()
    expect(notice).toHaveBeenCalledWith('doc', expect.stringContaining('损坏'))
    await expect(c.flush('doc')).rejects.toThrow('损坏')
    await expect(c.collect('doc', ref)).rejects.toThrow('损坏')
    expect(localStorage.getItem(key)).toBe('{damaged')
    c.dispose()
  })
  it('revives a live explicitly deleted reference after undo and retains it after the last citation disappears again', async () => {
    const service = createLocalReferenceServices(localStorage)
    const c = createReferenceLibraryController(service, localStorage)
    c.observe('doc', [ref])
    await c.flush('doc')
    await c.remove('doc', ref.id)
    c.observe('doc', [])
    c.observe('doc', [ref])
    c.observe('doc', [])
    await c.flush('doc')
    expect(c.get('doc').entries).toEqual([{ id: ref.id, text: ref.text }])
    expect(c.get('doc').deletedIds).toEqual([])
    expect(c.get('doc').highWater).toBe(ref.number)
    c.dispose()
    const reopened = createReferenceLibraryController(service, localStorage)
    expect((await reopened.load('doc')).entries).toEqual([{ id: ref.id, text: ref.text }])
    reopened.dispose()
  })
  it('does not revive persisted tombstones on cold load or later body reappearance', async () => {
    const service = createLocalReferenceServices(localStorage)
    await service.saveLibrary!('doc', { ...emptyReferenceLibrary(), deletedIds: [ref.id] })
    const c = createReferenceLibraryController(service, localStorage)
    c.observe('doc', [ref])
    await c.load('doc')
    c.observe('doc', [])
    c.observe('doc', [ref])
    await c.flush('doc')
    expect(c.get('doc').entries).toEqual([])
    expect(c.get('doc').deletedIds).toEqual([ref.id])
    c.dispose()
  })
  it('reuses the stable ID across raw DOI, DOI URL and structured metadata', async () => {
    const c = createReferenceLibraryController(createLocalReferenceServices(localStorage), localStorage)
    await c.collect('doc', { id: 'raw', text: '10.1000/ABC' })
    expect((await c.collect('doc', { id: 'url', text: 'https://doi.org/10.1000/abc' })).id).toBe('raw')
    expect((await c.collect('doc', { id: 'metadata', text: 'Formatted title', metadata: { doi: 'doi:10.1000/AbC' } })).id).toBe('raw')
    expect(c.get('doc').entries).toHaveLength(1)
    c.dispose()
  })
  it('deduplicates DOI URLs and supports old notes-only hosts', async () => {
    const service = createLocalReferenceServices(localStorage)
    const c = createReferenceLibraryController({ loadNotes: service.loadNotes, saveNote: service.saveNote }, localStorage)
    await c.collect('a', { id: 'one', text: 'First', metadata: { doi: 'https://doi.org/10.1000/ABC' } })
    expect((await c.collect('a', { id: 'two', text: 'Different formatting', metadata: { doi: '10.1000/abc' } })).id).toBe('one')
    c.dispose()
  })
})
