export type UiLocale = 'zh' | 'en' | 'ru'

const APP_EN_MESSAGES = {
  'workspace.documentWorkspace': 'Document workspace',
  'workspace.documentStatus': 'Document status',
  'workspace.articles': 'Articles',
  'workspace.outline': 'Outline',
  'workspace.sidebarViews': 'Left panel views',
  'workspace.documentOutline': 'On this page',
  'workspace.outlineChapters': '{count} sections',
  'workspace.outlineFor': 'Outline for {title}',
  'workspace.outlineHeading': 'Heading level {level}: {title}',
  'workspace.noHeadings': 'This article has no H1–H5 headings.',
  'workspace.workspace': 'Workspace',
  'workspace.toggleArticlePanel': 'Toggle article panel',
  'workspace.articleCatalog': 'Article catalog',
  'workspace.today': 'Today',
  'workspace.notUpdated': 'Not updated',
  'workspace.updated': 'Updated {value}',
  'workspace.notSavedYet': 'not saved yet',
  'workspace.justNow': 'just now',
  'workspace.articleState': 'Autosave {autosave} · checkpoint {checkpoint}',
  'workspace.articleCreated': 'Article created in Library: {title}.',
  'workspace.articleImported': 'Imported into Library: {title}.',
  'workspace.recoveryActions': 'Document recovery actions',
  'workspace.articleActions': 'Article actions',
  'workspace.recovery': 'Recovery',
  'workspace.newArticle': 'New article',
  'workspace.importMarkdown': 'Import Markdown',
  'workspace.dropMarkdown': 'Drop a Markdown file here, or',
  'workspace.chooseMarkdown': 'Choose file',
  'lifecycle.oneMarkdownFile': 'Import one Markdown file at a time.',
  'lifecycle.markdownFileType': 'Choose a .md or .markdown file.',
  'workspace.clear': 'Clear',
  'workspace.reset': 'Reset',
  'workspace.restoreModeCheckpoint': 'Restore mode checkpoint',
  'workspace.restoreReplacementCheckpoint': 'Restore replacement checkpoint',
  'workspace.noModeCheckpoint': 'No pre-mode-switch checkpoint is available.',
  'workspace.noReplacementCheckpoint': 'No destructive-replacement checkpoint is available.',
  'workspace.returnToEditingToRestore': 'Return to Source or Visual mode to restore.',
  'workspace.restoreModeCheckpointHint': 'Restore the latest pre-mode-switch checkpoint as a new revision.',
  'workspace.restoreReplacementCheckpointHint': 'Restore the latest destructive-replacement checkpoint as a new revision.',
  'workspace.resizeArticlePanel': 'Resize article panel',
  'workspace.editor': 'W-Editor workspace',
  'workspace.toolbar': 'W-Editor toolbar',
  'reader.profile': 'Reader profile',
  'reader.readOnlyPreview': 'Read-only preview',
  'workspace.savingVersion': 'Saving version…',
  'workspace.finalPreview': 'Final Cherry preview',
  'workspace.status': 'Workspace status',
  'workspace.words': '{count} words',
  'workspace.bodyWords': 'Body: {count}',
  'workspace.bodyWordsHelp': 'Prose in headings, paragraphs, lists and tables. Han characters count individually; other words and numbers count by token. Excludes references, citation numbers, formatting, punctuation, code and formulas.',
  'workspace.localRecoveryRequired': 'Local recovery required',
  'workspace.storedDataUnsafe': 'Stored {scope} data cannot be opened safely',
  'workspace.scope.document': 'document',
  'workspace.scope.workspace': 'workspace',
  'workspace.reason.unsupported': 'from an unsupported schema version',
  'workspace.reason.corrupt': 'corrupt or malformed',
  'workspace.envelopeReason': 'The envelope is {reason}. W-Editor has not overwritten the exact stored value.',
  'workspace.exportRawEnvelope': 'Export raw envelope',
  'workspace.clearAndReset': 'Clear and reset',
  'workspace.resetAvailable': 'Raw envelope exported. Reset is now available.',
  'workspace.resetEnabledHint': 'Clear the unreadable envelope and restore the fixed default.',
  'workspace.resetRequiresExportHint': 'Export the raw envelope before resetting.',
  'workspace.resetConfirmation': 'This removes only the unreadable local envelope and restores the fixed first-round default. Continue?',
  'workspace.confirmReset': 'Confirm reset',
  'workspace.protectedOperation': 'Protected operation',
  'search.documentTool': 'Document tool',
  'search.title': 'Search this article',
  'search.query': 'Search text',
  'search.clear': 'Clear search',
  'search.expandReplace': 'Show replacement controls',
  'search.collapseReplace': 'Hide replacement controls',
  'search.replacement': 'Replacement text',
  'search.matchCase': 'Match case',
  'search.noMatches': 'No matches.',
  'search.readOnly': 'Final preview search is read-only. Switch to Source or Visual to replace.',
  'search.previous': 'Previous',
  'search.next': 'Next',
  'search.replace': 'Replace',
  'search.replaceAll': 'Replace all',
  'search.search': 'Search',
  'search.scopeChanged': 'The active article or editor mode changed. Close search and open it again.',
  'search.revisionChanged': 'The document changed after this search. Search again before replacing.',
  'search.visualNoChange': 'The visual replacement did not change the active document.',
  'lineSpacing.title': 'Line spacing',
  'lineSpacing.single': 'Single · 1.25',
  'lineSpacing.compact': 'Compact · 1.50',
  'lineSpacing.standard': 'Standard · 1.75',
  'lineSpacing.double': 'Double · 2.00',
  'editorBoundary.start': 'Editable area starts',
  'editorBoundary.end': 'Editable area ends',
  'shortcuts.applicationSettings': 'Application settings',
  'shortcuts.title': 'Keyboard shortcuts',
  'shortcuts.help': 'Choose a command, arm its recorder, then press the shortcut on your keyboard. Bindings remain attached to stable command IDs.',
  'shortcuts.recordFor': 'Record shortcut for {command}',
  'shortcuts.unassigned': 'Unassigned',
  'shortcuts.pressShortcut': 'Press shortcut',
  'shortcuts.record': 'Record',
  'shortcuts.recording': 'Recording shortcut for {command}. Press a modifier and key, or a function key.',
  'shortcuts.resetDefaults': 'Reset to defaults',
  'shortcuts.apply': 'Apply shortcuts',
  'shortcuts.invalidCombination': 'Use a modifier-and-key combination or a function key.',
  'shortcuts.reserved': '{shortcut} is reserved by the browser or application.',
  'shortcuts.conflict': '{shortcut} is assigned to {existing}; assigning it to {command} would create a duplicate shortcut conflict.',
  'shortcuts.duplicate': '{shortcut} is assigned to both {first} and {second}.',
  'tablePicker.chooseSize': 'Choose table size',
  'tablePicker.tableSize': 'Table size',
  'tablePicker.cell.oneOne': '{columns} column by {rows} data row',
  'tablePicker.cell.oneMany': '{columns} column by {rows} data rows',
  'tablePicker.cell.manyOne': '{columns} columns by {rows} data row',
  'tablePicker.cell.manyMany': '{columns} columns by {rows} data rows',
  'tablePicker.status.oneOne': '{columns} column × {rows} data row',
  'tablePicker.status.oneMany': '{columns} column × {rows} data rows',
  'tablePicker.status.manyOne': '{columns} columns × {rows} data row',
  'tablePicker.status.manyMany': '{columns} columns × {rows} data rows',
  'tablePicker.instructions': 'Use the arrow keys to choose a size, Enter to insert, or Escape to cancel.',
  'tablePicker.insert': 'Insert table',
  'tablePicker.cancel': 'Cancel',
  'link.kicker': 'Link',
  'link.destination': 'Link destination',
  'link.url': 'URL',
  'richText.formatting': 'Text formatting',
  'richText.backgroundColor': 'Background color',
  'richText.textColor': 'Text color',
  'richText.rubyAnnotation': 'Ruby annotation',
  'richText.fontSize': 'Font size',
  'richText.baseText': 'Base text',
  'richText.rubyOrPinyin': 'Ruby annotation / pinyin',
  'richText.clearVisualOnly': 'Clear the current color in the Visual editor.',
  'color.title': 'Text and background color',
  'color.type': 'Color type',
  'color.text': 'Text',
  'color.background': 'Background',
  'color.clear': 'Clear color',
  'color.saturationBrightness': 'Choose saturation and brightness',
  'color.hue': 'Hue',
  'color.current': 'Current color; choose to apply',
  'color.recent': 'Recently used colors',
  'color.recentValue': 'Recently used {color}',
  'color.presets': 'System preset colors',
  'layout.cherryStructure': 'Cherry Markdown structure',
  'layout.columnSource': 'Column layout source',
  'layout.tabsSource': 'Tabs source',
  'layout.accordionSource': 'Accordion source',
  'layout.timelineSource': 'Timeline source',
  'panel.source': 'Panel source',
  'mermaid.source': 'Mermaid source',
  'mermaid.diagram': 'Mermaid diagram',
  'mermaid.typedDiagram': 'Mermaid {type}',
  'chart.invalidSyntax': 'Chart-table data could not be serialized to valid Cherry syntax.',
  'chart.noLongerSelected': 'The chart table is no longer selected.',
  'document.authoritativeRevision': 'Authoritative revision',
  'document.statistics': 'Document statistics',
  'document.revision': 'Revision',
  'document.words': 'Words',
  'document.characters': 'Characters',
  'document.charactersWithoutWhitespace': 'Characters without whitespace',
  'document.lines': 'Lines',
  'document.paragraphs': 'Paragraphs',
  'document.utf8Bytes': 'UTF-8 bytes',
  'lifecycle.operation.clear': 'Clear document',
  'lifecycle.unsavedTitle': 'Unsaved changes',
  'lifecycle.unsavedDiscardBody': '“{title}” has unsaved changes. Choose how to handle the text before switching articles.',
  'lifecycle.unsavedBody': '“{title}” has unsaved changes at revision {revision}. Choose how to continue.',
  'lifecycle.keepDraft': 'Keep draft',
  'lifecycle.exportAndContinue': 'Export and continue',
  'lifecycle.cancel': 'Cancel',
  'lifecycle.saveAndContinue': 'Save changes',
  'lifecycle.discardAndContinue': 'Discard changes',
  'lifecycle.saveHelp': 'Save the current article, then switch.',
  'lifecycle.discardHelp': 'Discard: restore the last saved text (or the initial text for a new article). The article itself is kept.',
  'lifecycle.operation.import': 'Import Markdown',
  'lifecycle.operation.reset': 'Reset to template',
  'lifecycle.destructiveTitle': '{operation}?',
  'lifecycle.destructiveBody': '{operation} will replace revision {revision} of “{title}”. The current Markdown will first become the latest destructive-replacement checkpoint.',
  'lifecycle.cancelled': '{operation} cancelled. No revision or checkpoint changed.',
  'lifecycle.completed': '{operation} completed as revision {revision}.',
  'lifecycle.invalidMarkdown': 'The selected file is not readable UTF-8 Markdown. No content or checkpoint was changed.',
  'lifecycle.failed': 'The document lifecycle operation failed.',
  'lifecycle.confirmationActive': 'A document lifecycle confirmation is already active.',
  'lifecycle.restoreTitle': 'Restore protected content?',
  'lifecycle.restoreBody': 'Restore the {checkpoint} checkpoint from revision {revision}? The current content will remain available through ordinary {mode} mode Undo.',
  'lifecycle.restore': 'Restore checkpoint',
  'lifecycle.checkpoint.preMode': 'pre-mode-switch',
  'lifecycle.checkpoint.preReplacement': 'pre-destructive-replace',
  'lifecycle.checkpointUnavailable': 'That checkpoint is not available for this article.',
  'lifecycle.restoreCancelled': 'Checkpoint restore cancelled. No revision or history changed.',
  'lifecycle.restored': 'Checkpoint restored as revision {revision}; Undo restores the replaced content.',
  'lifecycle.restoreRequiresEditing': 'Return to Source or Visual mode before restoring a checkpoint.',
  'lifecycle.activeModeChanged': 'The active editor mode changed before checkpoint restore.',
  'lifecycle.sourceUnavailable': 'The Source editor is not ready for checkpoint restore.',
  'lifecycle.visualUnavailable': 'The Visual editor is not ready for checkpoint restore.',
  'lifecycle.recoveryEnvelopeUnavailable': 'The stored recovery envelope is no longer available.',
  'lifecycle.recoveryDocumentUnknown': 'The recovery document is not part of the fixed catalog.',
  'lifecycle.openSource': 'Open source',
  'lifecycle.exportRawMarkdown': 'Export raw Markdown',
  'lifecycle.recover': 'Recover',
  'mode.group': 'Editor mode',
  'mode.source': 'Source',
  'mode.visual': 'Visual',
  'mode.preview': 'Preview',
  'mode.surface.source': 'Source editor surface',
  'mode.surface.visual': 'Visual editor surface',
  'mode.surface.preview': 'Preview editor surface',
  'language.zh': 'Chinese',
  'language.en': 'English',
  'language.ru': 'Russian',
  'theme.default': 'Default',
  'theme.dark': 'Dark',
  'theme.gray': 'Gray',
  'theme.abyss': 'Abyss',
  'theme.green': 'Fresh',
  'theme.red': 'Passion',
  'theme.violet': 'Elegant',
  'theme.blue': 'Quiet',
  'status.sync.failed': 'Synchronization needs attention',
  'status.sync.pending': 'Changes pending',
  'status.sync.running': 'Preparing mode',
  'status.sync.waitingComposition': 'Waiting for composition to finish',
  'status.sync.synchronized': 'All changes synchronized',
  'status.sync.unavailable': 'Synchronization status unavailable',
  'status.synchronization': 'Synchronization {status}',
  'status.autosave': 'Autosave {status}',
  'status.manualCheckpoint': 'Manual checkpoint {status}',
  'status.currentMode': '{mode} mode',
  'status.idle': 'idle',
  'status.pending': 'pending',
  'status.saving': 'saving',
  'status.saved': 'saved',
  'status.failed': 'failed',
  'status.synchronized': 'synchronized',
  'status.dirty': 'dirty',
  'status.clean': 'clean',
  'status.unavailableFinalPreview': 'Unavailable in final preview.',
  'status.unavailableCurrentMode': 'Unavailable in the current mode.',
  'status.alignmentUnavailable': 'Alignment accepts only paragraph and H1-H5 block ranges.',
  'status.manualSaveInProgress': 'A manual checkpoint is being saved.',
  'status.modeChangeInProgress': 'A mode change is already in progress.',
  'status.contentCommandsUnavailable': 'Document editing commands are unavailable in final preview.',
  'status.selectSourceText': 'Select source text before applying this mark.',
  'status.fullscreenUnavailable': 'Fullscreen is unavailable before the application surface is mounted.',
  'status.lifecycleInProgress': 'A protected document operation is in progress.',
  'feedback.applied': '{command} applied.',
  'feedback.removed': '{command} removed.',
  'feedback.inserted': '{command} inserted.',
  'feedback.noChange': '{command} made no change.',
  'feedback.completed': '{command} completed.',
  'feedback.editorOpened': '{editor} opened.',
  'feedback.modePreviewOpened': 'Final preview opened.',
  'feedback.modeReturned': 'Returned to {mode} mode.',
  'feedback.modeChanged': 'Mode changed to {mode}.',
  'feedback.languageChanged': 'Interface language changed to {language}.',
  'feedback.themeChanged': 'Interface theme changed to {theme}.',
  'feedback.themeChangedSessionOnly': 'Interface theme changed to {theme} for this session; browser storage is unavailable.',
  'feedback.lineSpacingChanged': 'Line spacing changed to {value}.',
  'feedback.lineSpacingChangedSessionOnly': 'Line spacing changed to {value} for this session; browser storage is unavailable.',
  'feedback.codeCopied': 'Code copied.',
  'feedback.codeCopyFailed': 'Code copy failed. Check clipboard permission.',
  'feedback.rawNodeUnavailable': 'The raw source node is no longer selected.',
  'feedback.nodeUnavailable': 'The selected {kind} is no longer available.',
  'feedback.tableInserted': '{size} table inserted.',
  'feedback.tableUnavailable': 'Table insertion was unavailable.',
  'feedback.shortcutsUpdated': 'Keyboard shortcuts updated.',
  'feedback.fullscreenEntered': 'Fullscreen entered.',
  'feedback.fullscreenExited': 'Fullscreen exited.',
  'feedback.externalDetail': 'Operation failed: {detail}',
  'feedback.validationDetail': 'Validation failed: {detail}',
  'feedback.fullscreenDetail': 'Fullscreen failed: {detail}',
  'feedback.exportDetail': 'Export failed: {detail}',
  'feedback.searchDetail': 'Search failed: {detail}',
  'feedback.statisticsDetail': 'Statistics failed: {detail}',
  'feedback.shortcutDetail': 'Shortcut settings failed: {detail}',
  'feedback.dedicatedEditorDetail': 'Editor update failed: {detail}',
  'feedback.dedicated.activeSurfaceRequired': 'Dedicated editors require an active editing surface.',
  'feedback.dedicated.planning': 'The app could not prepare the dedicated-editor update. Review the draft and retry.',
  'feedback.dedicated.revision': 'The document revision changed before Apply. Review the current content and retry.',
  'feedback.dedicated.staleSelection': 'The selection changed before Apply. Reopen the target or review the draft and retry.',
  'feedback.dedicated.transaction': 'The dedicated-editor transaction was rejected. Review the draft and retry.',
  'feedback.dedicated.formulaContextUnavailable': 'The formula editing context is unavailable. Reopen the picker and retry.',
  'feedback.dedicated.sourceFormulaUnavailable': 'The Source editor surface is unavailable. Review the formula and retry.',
  'feedback.dedicated.visualFormulaUnavailable': 'The Visual editor surface is unavailable. Review the formula and retry.',
  'feedback.dedicated.staleFormulaSelection': 'The selection changed before Apply. Reopen the target or review the formula and retry.',
  'feedback.dedicated.formulaUnavailable': 'The selected formula is no longer available for this update. Review the formula and retry.',
  'feedback.dedicated.codeContextUnavailable': 'The code-block editing context is unavailable. Reopen the editor and retry.',
  'feedback.dedicated.sourceDraftUnavailable': 'The Source editor surface is unavailable. Review the draft and retry.',
  'feedback.dedicated.visualDraftUnavailable': 'The Visual editor surface is unavailable. Review the draft and retry.',
  'feedback.dedicated.codeUnavailable': 'The selected code block is no longer available for this update. Review the draft and retry.',
  'feedback.dedicated.panelContextUnavailable': 'The panel editing context is unavailable. Reopen the editor and retry.',
  'feedback.dedicated.panelCommandUnavailable': 'The panel command is no longer available. Reopen the editor and retry.',
  'feedback.dedicated.panelUnavailable': 'The selected panel is no longer available for this update. Review the draft and retry.',
  'validation.panelSource': 'Enter one complete {panel} source with a title and body.',
  'validation.panelCommand': 'The selected panel command is unavailable.',
  'validation.columnLayoutSource': 'Enter one complete {layout} source with every required column.',
  'validation.disclosureSource': 'Enter valid {layout} source with all required labeled sections.',
  'validation.timelineSource': 'Enter valid {timeline} source with a title and at least one item.',
  'validation.invalidDraft': 'The draft is not valid for this editor.',
  'export.markdownDownloaded': 'Markdown revision {revision} downloaded.',
  'export.renderedDownloaded': '{format} revision {revision} downloaded.',
  'export.pdfDownloaded': 'PDF revision {revision} downloaded.',
  'export.pdfDownloadedWithOmittedRemoteImages': 'PDF revision {revision} downloaded; remote images omitted: {count}.',
  'export.screenshotDownloaded': 'Long screenshot revision {revision} downloaded.',
  'export.screenshotDownloadedWithOmittedRemoteImages': 'Long screenshot revision {revision} downloaded; remote images omitted: {count}.',
  'export.rawRecoveryExported': 'Raw recovery data exported.',
} as const

const APP_MESSAGES = Object.freeze({
  en: Object.freeze(APP_EN_MESSAGES),
  zh: Object.freeze({
    'workspace.documentWorkspace': '文档工作区',
    'workspace.documentStatus': '文档状态',
    'workspace.articles': '文章',
    'workspace.outline': '目录',
    'workspace.sidebarViews': '左侧面板视图',
    'workspace.documentOutline': '本文目录',
    'workspace.outlineChapters': '{count} 个章节',
    'workspace.outlineFor': '“{title}”的文章目录',
    'workspace.outlineHeading': '{level} 级标题：{title}',
    'workspace.noHeadings': '当前文章没有 H1–H5 标题。',
    'workspace.workspace': '工作区',
    'workspace.toggleArticlePanel': '切换文章面板',
    'workspace.articleCatalog': '文章目录',
    'workspace.today': '今天',
    'workspace.notUpdated': '未更新',
    'workspace.updated': '更新于 {value}',
    'workspace.notSavedYet': '尚未保存',
    'workspace.justNow': '刚刚',
    'workspace.articleState': '自动保存 {autosave} · 检查点 {checkpoint}',
    'workspace.articleCreated': '已在文章库创建：{title}。',
    'workspace.articleImported': '已导入文章库：{title}。',
    'workspace.recoveryActions': '文档恢复操作',
    'workspace.articleActions': '文章操作',
    'workspace.recovery': '恢复',
    'workspace.newArticle': '新建文章',
    'workspace.importMarkdown': '导入 Markdown',
  'workspace.dropMarkdown': '拖入 Markdown 文件，或',
  'workspace.chooseMarkdown': '选择文件',
  'lifecycle.oneMarkdownFile': '一次只能导入一个 Markdown 文件。',
  'lifecycle.markdownFileType': '请选择 .md 或 .markdown 文件。',
    'workspace.clear': '清空',
    'workspace.reset': '重置',
    'workspace.restoreModeCheckpoint': '恢复模式检查点',
    'workspace.restoreReplacementCheckpoint': '恢复替换检查点',
    'workspace.noModeCheckpoint': '没有可用的模式切换前检查点。',
    'workspace.noReplacementCheckpoint': '没有可用的破坏性替换前检查点。',
    'workspace.returnToEditingToRestore': '请返回源码或可视化模式后再恢复。',
    'workspace.restoreModeCheckpointHint': '将最新的模式切换前检查点恢复为新修订。',
    'workspace.restoreReplacementCheckpointHint': '将最新的破坏性替换前检查点恢复为新修订。',
    'workspace.resizeArticlePanel': '调整文章面板大小',
    'workspace.editor': 'W-Editor 工作区',
    'workspace.toolbar': 'W-Editor 工具栏',
    'reader.profile': '阅读模式',
    'reader.readOnlyPreview': '只读预览',
    'workspace.savingVersion': '正在保存版本…',
    'workspace.finalPreview': '最终 Cherry 预览',
    'workspace.status': '工作区状态',
    'workspace.words': '{count} 个词',
    'workspace.bodyWords': '正文 {count} 字',
    'workspace.bodyWordsHelp': '统计标题、段落、列表和表格正文；中文逐字计数，英文和数字按词计数。不计参考文献、引用编号、格式标记、标点、代码及公式。',
    'workspace.localRecoveryRequired': '需要本地恢复',
    'workspace.storedDataUnsafe': '已存储的{scope}数据无法安全打开',
    'workspace.scope.document': '文档',
    'workspace.scope.workspace': '工作区',
    'workspace.reason.unsupported': '来自不支持的架构版本',
    'workspace.reason.corrupt': '已损坏或格式不正确',
    'workspace.envelopeReason': '该数据包{reason}。W-Editor 尚未覆盖原始存储值。',
    'workspace.exportRawEnvelope': '导出原始数据包',
    'workspace.clearAndReset': '清除并重置',
    'workspace.resetAvailable': '原始数据包已导出，现在可以重置。',
    'workspace.resetEnabledHint': '清除无法读取的数据包并恢复固定默认值。',
    'workspace.resetRequiresExportHint': '重置前请先导出原始数据包。',
    'workspace.resetConfirmation': '这只会删除无法读取的本地数据包并恢复固定的首轮默认值。是否继续？',
    'workspace.confirmReset': '确认重置',
    'workspace.protectedOperation': '受保护操作',
    'search.documentTool': '文档工具',
    'search.title': '搜索本文',
    'search.query': '搜索文本',
    'search.clear': '清除搜索',
    'search.expandReplace': '展开替换控件',
    'search.collapseReplace': '收起替换控件',
    'search.replacement': '替换文本',
    'search.matchCase': '区分大小写',
    'search.noMatches': '没有匹配项。',
    'search.readOnly': '最终预览中的搜索为只读。请切换到源码或可视化模式后替换。',
    'search.previous': '上一个',
    'search.next': '下一个',
    'search.replace': '替换',
    'search.replaceAll': '全部替换',
    'search.search': '搜索',
    'search.scopeChanged': '活动文章或编辑器模式已更改。请关闭搜索后重新打开。',
    'search.revisionChanged': '文档在本次搜索后已更改。请重新搜索再替换。',
    'search.visualNoChange': '可视化替换未更改活动文档。',
    'lineSpacing.title': '行间距',
    'lineSpacing.single': '单倍 · 1.25',
    'lineSpacing.compact': '紧凑 · 1.50',
    'lineSpacing.standard': '标准 · 1.75',
    'lineSpacing.double': '双倍 · 2.00',
    'editorBoundary.start': '可编辑区开始',
    'editorBoundary.end': '可编辑区结束',
    'shortcuts.applicationSettings': '应用设置',
    'shortcuts.title': '键盘快捷键',
    'shortcuts.help': '选择命令并启用录制器，然后按下键盘快捷键。绑定始终关联稳定的命令 ID。',
    'shortcuts.recordFor': '为 {command} 录制快捷键',
    'shortcuts.unassigned': '未分配',
    'shortcuts.pressShortcut': '请按快捷键',
    'shortcuts.record': '录制',
    'shortcuts.recording': '正在为 {command} 录制快捷键。请按修饰键与普通键组合，或功能键。',
    'shortcuts.resetDefaults': '恢复默认值',
    'shortcuts.apply': '应用快捷键',
    'shortcuts.invalidCombination': '请使用修饰键与普通键组合，或功能键。',
    'shortcuts.reserved': '{shortcut} 已被浏览器或应用保留。',
    'shortcuts.conflict': '{shortcut} 已分配给 {existing}；再分配给 {command} 会产生重复快捷键冲突。',
    'shortcuts.duplicate': '{shortcut} 同时分配给 {first} 和 {second}。',
    'tablePicker.chooseSize': '选择表格大小',
    'tablePicker.tableSize': '表格尺寸',
    'tablePicker.cell.oneOne': '{columns} 列乘 {rows} 数据行',
    'tablePicker.cell.oneMany': '{columns} 列乘 {rows} 数据行',
    'tablePicker.cell.manyOne': '{columns} 列乘 {rows} 数据行',
    'tablePicker.cell.manyMany': '{columns} 列乘 {rows} 数据行',
    'tablePicker.status.oneOne': '{columns} 列 × {rows} 数据行',
    'tablePicker.status.oneMany': '{columns} 列 × {rows} 数据行',
    'tablePicker.status.manyOne': '{columns} 列 × {rows} 数据行',
    'tablePicker.status.manyMany': '{columns} 列 × {rows} 数据行',
    'tablePicker.instructions': '使用方向键选择尺寸，按 Enter 插入，或按 Escape 取消。',
    'tablePicker.insert': '插入表格',
    'tablePicker.cancel': '取消',
    'link.kicker': '链接',
    'link.destination': '链接目标',
    'link.url': 'URL',
    'richText.formatting': '文本格式',
    'richText.backgroundColor': '背景颜色',
    'richText.textColor': '文字颜色',
    'richText.rubyAnnotation': '注音',
    'richText.fontSize': '字号',
    'richText.baseText': '基础文字',
    'richText.rubyOrPinyin': '注音 / 拼音',
    'richText.clearVisualOnly': '请在可视化编辑器中清除当前颜色。',
    'color.title': '文字和背景颜色',
    'color.type': '颜色类型',
    'color.text': '文字',
    'color.background': '背景',
    'color.clear': '清除颜色',
    'color.saturationBrightness': '选择饱和度和亮度',
    'color.hue': '色相',
    'color.current': '当前颜色，选择后应用',
    'color.recent': '最近使用颜色',
    'color.recentValue': '最近使用 {color}',
    'color.presets': '系统预设颜色',
    'layout.cherryStructure': 'Cherry Markdown 结构',
    'layout.columnSource': '双栏源码',
    'layout.tabsSource': '标签页源码',
    'layout.accordionSource': '手风琴源码',
    'layout.timelineSource': '时间线源码',
    'panel.source': '面板源码',
    'mermaid.source': 'Mermaid 源码',
    'mermaid.diagram': 'Mermaid 图表',
    'mermaid.typedDiagram': 'Mermaid {type}',
    'chart.invalidSyntax': '图表表格数据无法序列化为有效的 Cherry 语法。',
    'chart.noLongerSelected': '该图表表格已不再被选中。',
    'document.authoritativeRevision': '权威修订',
    'document.statistics': '文档统计',
    'document.revision': '修订',
    'document.words': '词数',
    'document.characters': '字符数',
    'document.charactersWithoutWhitespace': '不含空白的字符数',
    'document.lines': '行数',
    'document.paragraphs': '段落数',
    'document.utf8Bytes': 'UTF-8 字节数',
    'lifecycle.operation.clear': '清空文档',
    'lifecycle.unsavedTitle': '存在未保存更改',
    'lifecycle.unsavedDiscardBody': '“{title}”的正文尚未保存。请选择如何处理，再切换文章。',
    'lifecycle.unsavedBody': '“{title}”在修订 {revision} 有未保存更改。请选择继续方式。',
    'lifecycle.keepDraft': '保留草稿',
    'lifecycle.exportAndContinue': '导出并继续',
    'lifecycle.cancel': '取消',
    'lifecycle.saveAndContinue': '保存修改',
  'lifecycle.discardAndContinue': '丢弃修改',
  'lifecycle.saveHelp': '保存当前文章后切换。',
  'lifecycle.discardHelp': '丢弃修改：恢复最近一次保存的正文；新文章恢复初始正文。不会删除文章。',
    'lifecycle.operation.import': '导入 Markdown',
    'lifecycle.operation.reset': '重置为模板',
    'lifecycle.destructiveTitle': '{operation}？',
    'lifecycle.destructiveBody': '{operation}将替换“{title}”的修订 {revision}。当前 Markdown 会先保存为最新的破坏性替换前检查点。',
    'lifecycle.cancelled': '已取消{operation}，修订和检查点均未更改。',
    'lifecycle.completed': '{operation}已完成，当前为修订 {revision}。',
    'lifecycle.invalidMarkdown': '所选文件不是可读取的 UTF-8 Markdown；内容和检查点均未更改。',
    'lifecycle.failed': '文档生命周期操作失败。',
    'lifecycle.confirmationActive': '已有文档生命周期确认正在进行。',
    'lifecycle.restoreTitle': '恢复受保护内容？',
    'lifecycle.restoreBody': '是否恢复修订 {revision} 的{checkpoint}检查点？当前内容仍可通过普通的{mode}模式撤销恢复。',
    'lifecycle.restore': '恢复检查点',
    'lifecycle.checkpoint.preMode': '模式切换前',
    'lifecycle.checkpoint.preReplacement': '破坏性替换前',
    'lifecycle.checkpointUnavailable': '此文章没有该检查点。',
    'lifecycle.restoreCancelled': '已取消检查点恢复；修订和历史记录均未更改。',
    'lifecycle.restored': '检查点已恢复为修订 {revision}；撤销可恢复被替换的内容。',
    'lifecycle.restoreRequiresEditing': '请返回源码或可视化模式后再恢复检查点。',
    'lifecycle.activeModeChanged': '恢复检查点前活动编辑模式已更改。',
    'lifecycle.sourceUnavailable': '源码编辑器尚未准备好恢复检查点。',
    'lifecycle.visualUnavailable': '可视化编辑器尚未准备好恢复检查点。',
    'lifecycle.recoveryEnvelopeUnavailable': '已存储的恢复数据包已不可用。',
    'lifecycle.recoveryDocumentUnknown': '恢复文档不在固定目录中。',
    'lifecycle.openSource': '打开源码',
    'lifecycle.exportRawMarkdown': '导出原始 Markdown',
    'lifecycle.recover': '恢复',
    'mode.group': '编辑模式',
    'mode.source': '源码',
    'mode.visual': '可视化',
    'mode.preview': '预览',
    'mode.surface.source': '源码编辑器区域',
    'mode.surface.visual': '可视化编辑器区域',
    'mode.surface.preview': '预览区域',
    'language.zh': '中文',
    'language.en': '英语',
    'language.ru': '俄语',
    'theme.default': '默认',
    'theme.dark': '暗黑',
    'theme.gray': '沉稳',
    'theme.abyss': '深海',
    'theme.green': '清新',
    'theme.red': '热情',
    'theme.violet': '淡雅',
    'theme.blue': '清幽',
    'status.sync.failed': '同步需要处理',
    'status.sync.pending': '更改待同步',
    'status.sync.running': '正在准备模式',
    'status.sync.waitingComposition': '等待输入法组合结束',
    'status.sync.synchronized': '所有更改已同步',
    'status.sync.unavailable': '同步状态不可用',
    'status.synchronization': '同步 {status}',
    'status.autosave': '自动保存 {status}',
    'status.manualCheckpoint': '手动检查点 {status}',
    'status.currentMode': '{mode}模式',
    'status.idle': '空闲',
    'status.pending': '待处理',
    'status.saving': '保存中',
    'status.saved': '已保存',
    'status.failed': '失败',
    'status.synchronized': '已同步',
    'status.dirty': '有更改',
    'status.clean': '干净',
    'status.unavailableFinalPreview': '最终预览中不可用。',
    'status.unavailableCurrentMode': '当前模式中不可用。',
    'status.alignmentUnavailable': '对齐只接受段落及 H1–H5 块范围。',
    'status.manualSaveInProgress': '正在保存手动检查点。',
    'status.modeChangeInProgress': '已有模式切换正在进行。',
    'status.contentCommandsUnavailable': '最终预览中无法使用文档编辑命令。',
    'status.selectSourceText': '应用此标记前请选择源码文本。',
    'status.fullscreenUnavailable': '应用界面挂载前无法进入全屏。',
    'status.lifecycleInProgress': '受保护的文档操作正在进行。',
    'feedback.applied': '已应用 {command}。',
    'feedback.removed': '已移除 {command}。',
    'feedback.inserted': '已插入 {command}。',
    'feedback.noChange': '{command} 未产生更改。',
    'feedback.completed': '{command} 已完成。',
    'feedback.editorOpened': '已打开{editor}。',
    'feedback.modePreviewOpened': '已打开最终预览。',
    'feedback.modeReturned': '已返回{mode}模式。',
    'feedback.modeChanged': '已切换到{mode}模式。',
    'feedback.languageChanged': '界面语言已切换为{language}。',
    'feedback.themeChanged': '界面主题已切换为{theme}。',
    'feedback.themeChangedSessionOnly': '本次会话已切换为{theme}主题；浏览器存储不可用。',
    'feedback.lineSpacingChanged': '行间距已调整为{value}。',
    'feedback.lineSpacingChangedSessionOnly': '本次会话已调整为{value}行间距；浏览器存储不可用。',
    'feedback.codeCopied': '代码已复制。',
    'feedback.codeCopyFailed': '代码复制失败，请检查剪贴板权限。',
    'feedback.rawNodeUnavailable': '原始源码节点已不再被选中。',
    'feedback.nodeUnavailable': '所选{kind}已不可用。',
    'feedback.tableInserted': '已插入 {size} 表格。',
    'feedback.tableUnavailable': '表格插入不可用。',
    'feedback.shortcutsUpdated': '键盘快捷键已更新。',
    'feedback.fullscreenEntered': '已进入全屏。',
    'feedback.fullscreenExited': '已退出全屏。',
    'feedback.externalDetail': '操作失败：{detail}',
    'feedback.validationDetail': '验证失败：{detail}',
    'feedback.fullscreenDetail': '全屏失败：{detail}',
    'feedback.exportDetail': '导出失败：{detail}',
    'feedback.searchDetail': '搜索失败：{detail}',
    'feedback.statisticsDetail': '统计失败：{detail}',
    'feedback.shortcutDetail': '快捷键设置失败：{detail}',
    'feedback.dedicatedEditorDetail': '编辑器更新失败：{detail}',
    'feedback.dedicated.activeSurfaceRequired': '专用编辑器需要一个活动的编辑区域。',
    'feedback.dedicated.planning': '应用无法准备专用编辑器更新。请检查草稿后重试。',
    'feedback.dedicated.revision': '应用前文档修订已更改。请检查当前内容后重试。',
    'feedback.dedicated.staleSelection': '应用前选择已更改。请重新打开目标或检查草稿后重试。',
    'feedback.dedicated.transaction': '专用编辑器事务被拒绝。请检查草稿后重试。',
    'feedback.dedicated.formulaContextUnavailable': '公式编辑上下文不可用。请重新打开选择器后重试。',
    'feedback.dedicated.sourceFormulaUnavailable': '源码编辑器区域不可用。请检查公式后重试。',
    'feedback.dedicated.visualFormulaUnavailable': '可视化编辑器区域不可用。请检查公式后重试。',
    'feedback.dedicated.staleFormulaSelection': '应用前选择已更改。请重新打开目标或检查公式后重试。',
    'feedback.dedicated.formulaUnavailable': '所选公式已无法更新。请检查公式后重试。',
    'feedback.dedicated.codeContextUnavailable': '代码块编辑上下文不可用。请重新打开编辑器后重试。',
    'feedback.dedicated.sourceDraftUnavailable': '源码编辑器区域不可用。请检查草稿后重试。',
    'feedback.dedicated.visualDraftUnavailable': '可视化编辑器区域不可用。请检查草稿后重试。',
    'feedback.dedicated.codeUnavailable': '所选代码块已无法更新。请检查草稿后重试。',
    'feedback.dedicated.panelContextUnavailable': '面板编辑上下文不可用。请重新打开编辑器后重试。',
    'feedback.dedicated.panelCommandUnavailable': '面板命令已不可用。请重新打开编辑器后重试。',
    'feedback.dedicated.panelUnavailable': '所选面板已无法更新。请检查草稿后重试。',
    'validation.panelSource': '请输入一个包含标题和正文的完整{panel}源码。',
    'validation.panelCommand': '所选面板命令不可用。',
    'validation.columnLayoutSource': '请输入一个包含所有必需分栏的完整{layout}源码。',
    'validation.disclosureSource': '请输入包含全部必需标题分区的有效{layout}源码。',
    'validation.timelineSource': '请输入包含标题和至少一个条目的有效{timeline}源码。',
    'validation.invalidDraft': '此编辑器中的草稿无效。',
    'export.markdownDownloaded': 'Markdown 修订 {revision} 已下载。',
    'export.renderedDownloaded': '{format} 修订 {revision} 已下载。',
    'export.pdfDownloaded': 'PDF 修订 {revision} 已下载。',
    'export.pdfDownloadedWithOmittedRemoteImages': 'PDF 修订 {revision} 已下载；因跨域限制未嵌入的远程图片：{count}。',
    'export.screenshotDownloaded': '修订 {revision} 的长截图已下载。',
    'export.screenshotDownloadedWithOmittedRemoteImages': '修订 {revision} 的长截图已下载；因跨域限制未嵌入的远程图片：{count}。',
    'export.rawRecoveryExported': '原始恢复数据已导出。',
  } satisfies Record<keyof typeof APP_EN_MESSAGES, string>),
  ru: Object.freeze({
    'workspace.documentWorkspace': 'Рабочее пространство документа',
    'workspace.documentStatus': 'Статус документа',
    'workspace.articles': 'Статьи',
    'workspace.outline': 'Структура',
    'workspace.sidebarViews': 'Режимы левой панели',
    'workspace.documentOutline': 'Оглавление',
    'workspace.outlineChapters': 'Разделов: {count}',
    'workspace.outlineFor': 'Структура статьи «{title}»',
    'workspace.outlineHeading': 'Заголовок уровня {level}: {title}',
    'workspace.noHeadings': 'В статье нет заголовков H1–H5.',
    'workspace.workspace': 'Рабочая область',
    'workspace.toggleArticlePanel': 'Переключить панель статей',
    'workspace.articleCatalog': 'Каталог статей',
    'workspace.today': 'Сегодня',
    'workspace.notUpdated': 'Не обновлялось',
    'workspace.updated': 'Обновлено: {value}',
    'workspace.notSavedYet': 'ещё не сохранено',
    'workspace.justNow': 'только что',
    'workspace.articleState': 'Автосохранение: {autosave} · контрольная точка: {checkpoint}',
    'workspace.articleCreated': 'Статья создана в библиотеке: {title}.',
    'workspace.articleImported': 'Импортировано в библиотеку: {title}.',
    'workspace.recoveryActions': 'Действия восстановления документа',
    'workspace.articleActions': 'Действия со статьёй',
    'workspace.recovery': 'Восстановление',
    'workspace.newArticle': 'Новая статья',
    'workspace.importMarkdown': 'Импортировать Markdown',
  'workspace.dropMarkdown': 'Перетащите файл Markdown или',
  'workspace.chooseMarkdown': 'Выбрать файл',
  'lifecycle.oneMarkdownFile': 'Импортируйте по одному файлу Markdown.',
  'lifecycle.markdownFileType': 'Выберите файл .md или .markdown.',
    'workspace.clear': 'Очистить',
    'workspace.reset': 'Сбросить',
    'workspace.restoreModeCheckpoint': 'Восстановить точку режима',
    'workspace.restoreReplacementCheckpoint': 'Восстановить точку замены',
    'workspace.noModeCheckpoint': 'Контрольная точка до смены режима недоступна.',
    'workspace.noReplacementCheckpoint': 'Контрольная точка до разрушительной замены недоступна.',
    'workspace.returnToEditingToRestore': 'Вернитесь в режим исходника или визуальный режим для восстановления.',
    'workspace.restoreModeCheckpointHint': 'Восстановить последнюю точку до смены режима как новую редакцию.',
    'workspace.restoreReplacementCheckpointHint': 'Восстановить последнюю точку до разрушительной замены как новую редакцию.',
    'workspace.resizeArticlePanel': 'Изменить размер панели статей',
    'workspace.editor': 'Рабочая область W-Editor',
    'workspace.toolbar': 'Панель инструментов W-Editor',
    'reader.profile': 'Режим чтения',
    'reader.readOnlyPreview': 'Предпросмотр только для чтения',
    'workspace.savingVersion': 'Сохранение версии…',
    'workspace.finalPreview': 'Итоговый просмотр Cherry',
    'workspace.status': 'Статус рабочей области',
    'workspace.words': 'Слов: {count}',
    'workspace.bodyWords': 'Текст: {count}',
    'workspace.bodyWordsHelp': 'Текст заголовков, абзацев, списков и таблиц. Иероглифы считаются отдельно, остальные слова и числа — по токенам. Без библиографии, номеров цитат, разметки, пунктуации, кода и формул.',
    'workspace.localRecoveryRequired': 'Требуется локальное восстановление',
    'workspace.storedDataUnsafe': 'Сохранённые данные ({scope}) нельзя безопасно открыть',
    'workspace.scope.document': 'документ',
    'workspace.scope.workspace': 'рабочая область',
    'workspace.reason.unsupported': 'из неподдерживаемой версии схемы',
    'workspace.reason.corrupt': 'повреждены или имеют неверный формат',
    'workspace.envelopeReason': 'Пакет данных {reason}. W-Editor не перезаписал точное сохранённое значение.',
    'workspace.exportRawEnvelope': 'Экспортировать исходный пакет',
    'workspace.clearAndReset': 'Очистить и сбросить',
    'workspace.resetAvailable': 'Исходный пакет экспортирован. Теперь доступен сброс.',
    'workspace.resetEnabledHint': 'Удалить нечитаемый пакет и восстановить фиксированное значение по умолчанию.',
    'workspace.resetRequiresExportHint': 'Экспортируйте исходный пакет перед сбросом.',
    'workspace.resetConfirmation': 'Будет удалён только нечитаемый локальный пакет и восстановлено фиксированное значение первого этапа. Продолжить?',
    'workspace.confirmReset': 'Подтвердить сброс',
    'workspace.protectedOperation': 'Защищённая операция',
    'search.documentTool': 'Инструмент документа',
    'search.title': 'Поиск по статье',
    'search.query': 'Текст поиска',
    'search.clear': 'Очистить поиск',
    'search.expandReplace': 'Показать элементы замены',
    'search.collapseReplace': 'Скрыть элементы замены',
    'search.replacement': 'Текст для замены',
    'search.matchCase': 'Учитывать регистр',
    'search.noMatches': 'Совпадений нет.',
    'search.readOnly': 'Поиск в итоговом просмотре доступен только для чтения. Для замены переключитесь в исходник или визуальный режим.',
    'search.previous': 'Предыдущее',
    'search.next': 'Следующее',
    'search.replace': 'Заменить',
    'search.replaceAll': 'Заменить всё',
    'search.search': 'Поиск',
    'search.scopeChanged': 'Активная статья или режим редактора изменились. Закройте поиск и откройте его снова.',
    'search.revisionChanged': 'Документ изменился после поиска. Выполните поиск снова перед заменой.',
    'search.visualNoChange': 'Визуальная замена не изменила активный документ.',
    'lineSpacing.title': 'Межстрочный интервал',
    'lineSpacing.single': 'Одинарный · 1.25',
    'lineSpacing.compact': 'Компактный · 1.50',
    'lineSpacing.standard': 'Стандартный · 1.75',
    'lineSpacing.double': 'Двойной · 2.00',
    'editorBoundary.start': 'Начало области редактирования',
    'editorBoundary.end': 'Конец области редактирования',
    'shortcuts.applicationSettings': 'Настройки приложения',
    'shortcuts.title': 'Сочетания клавиш',
    'shortcuts.help': 'Выберите команду, включите запись и нажмите сочетание клавиш. Привязки остаются связанными со стабильными ID команд.',
    'shortcuts.recordFor': 'Записать сочетание для {command}',
    'shortcuts.unassigned': 'Не назначено',
    'shortcuts.pressShortcut': 'Нажмите сочетание',
    'shortcuts.record': 'Записать',
    'shortcuts.recording': 'Запись сочетания для {command}. Нажмите модификатор с клавишей или функциональную клавишу.',
    'shortcuts.resetDefaults': 'Восстановить значения',
    'shortcuts.apply': 'Применить сочетания',
    'shortcuts.invalidCombination': 'Используйте модификатор с клавишей или функциональную клавишу.',
    'shortcuts.reserved': '{shortcut} зарезервировано браузером или приложением.',
    'shortcuts.conflict': '{shortcut} назначено команде {existing}; назначение команде {command} создаст конфликт.',
    'shortcuts.duplicate': '{shortcut} назначено обеим командам: {first} и {second}.',
    'tablePicker.chooseSize': 'Выберите размер таблицы',
    'tablePicker.tableSize': 'Размер таблицы',
    'tablePicker.cell.oneOne': '{columns} столбец на {rows} строку данных',
    'tablePicker.cell.oneMany': '{columns} столбец на {rows} строк данных',
    'tablePicker.cell.manyOne': '{columns} столбца на {rows} строку данных',
    'tablePicker.cell.manyMany': '{columns} столбца на {rows} строк данных',
    'tablePicker.status.oneOne': '{columns} столбец × {rows} строка данных',
    'tablePicker.status.oneMany': '{columns} столбец × {rows} строк данных',
    'tablePicker.status.manyOne': '{columns} столбца × {rows} строка данных',
    'tablePicker.status.manyMany': '{columns} столбца × {rows} строк данных',
    'tablePicker.instructions': 'Выберите размер стрелками, нажмите Enter для вставки или Escape для отмены.',
    'tablePicker.insert': 'Вставить таблицу',
    'tablePicker.cancel': 'Отмена',
    'link.kicker': 'Ссылка',
    'link.destination': 'Адрес ссылки',
    'link.url': 'URL',
    'richText.formatting': 'Форматирование текста',
    'richText.backgroundColor': 'Цвет фона',
    'richText.textColor': 'Цвет текста',
    'richText.rubyAnnotation': 'Аннотация ruby',
    'richText.fontSize': 'Размер шрифта',
    'richText.baseText': 'Основной текст',
    'richText.rubyOrPinyin': 'Аннотация ruby / пиньинь',
    'richText.clearVisualOnly': 'Очистите текущий цвет в визуальном редакторе.',
    'color.title': 'Цвет текста и фона',
    'color.type': 'Тип цвета',
    'color.text': 'Текст',
    'color.background': 'Фон',
    'color.clear': 'Очистить цвет',
    'color.saturationBrightness': 'Выберите насыщенность и яркость',
    'color.hue': 'Оттенок',
    'color.current': 'Текущий цвет; выберите для применения',
    'color.recent': 'Недавно использованные цвета',
    'color.recentValue': 'Недавний цвет {color}',
    'color.presets': 'Системные цвета',
    'layout.cherryStructure': 'Структура Cherry Markdown',
    'layout.columnSource': 'Исходник макета колонок',
    'layout.tabsSource': 'Исходник вкладок',
    'layout.accordionSource': 'Исходник аккордеона',
    'layout.timelineSource': 'Исходник временной шкалы',
    'panel.source': 'Исходник панели',
    'mermaid.source': 'Исходник Mermaid',
    'mermaid.diagram': 'Диаграмма Mermaid',
    'mermaid.typedDiagram': 'Mermaid {type}',
    'chart.invalidSyntax': 'Данные таблицы диаграммы нельзя сериализовать в корректный синтаксис Cherry.',
    'chart.noLongerSelected': 'Таблица диаграммы больше не выбрана.',
    'document.authoritativeRevision': 'Авторитетная редакция',
    'document.statistics': 'Статистика документа',
    'document.revision': 'Редакция',
    'document.words': 'Слова',
    'document.characters': 'Символы',
    'document.charactersWithoutWhitespace': 'Символы без пробелов',
    'document.lines': 'Строки',
    'document.paragraphs': 'Абзацы',
    'document.utf8Bytes': 'Байты UTF-8',
    'lifecycle.operation.clear': 'Очистить документ',
    'lifecycle.unsavedTitle': 'Есть несохранённые изменения',
    'lifecycle.unsavedDiscardBody': 'В статье «{title}» есть несохранённые изменения в редакции {revision}. Выберите действие.',
    'lifecycle.unsavedBody': 'В статье «{title}» есть несохранённые изменения в редакции {revision}. Выберите действие.',
    'lifecycle.keepDraft': 'Сохранить черновик',
    'lifecycle.exportAndContinue': 'Экспортировать и продолжить',
    'lifecycle.cancel': 'Отмена',
    'lifecycle.saveAndContinue': 'Сохранить изменения',
  'lifecycle.discardAndContinue': 'Отбросить изменения',
  'lifecycle.saveHelp': 'Сохранить статью и перейти.',
  'lifecycle.discardHelp': 'Отбросить: восстановить последний сохранённый текст (для новой статьи — исходный). Статья не удаляется.',
    'lifecycle.operation.import': 'Импортировать Markdown',
    'lifecycle.operation.reset': 'Сбросить к шаблону',
    'lifecycle.destructiveTitle': '{operation}?',
    'lifecycle.destructiveBody': '{operation} заменит редакцию {revision} документа «{title}». Текущий Markdown сначала станет последней контрольной точкой до разрушительной замены.',
    'lifecycle.cancelled': '{operation} отменено. Редакция и контрольная точка не изменены.',
    'lifecycle.completed': '{operation} завершено как редакция {revision}.',
    'lifecycle.invalidMarkdown': 'Выбранный файл не является читаемым UTF-8 Markdown. Содержимое и контрольная точка не изменены.',
    'lifecycle.failed': 'Ошибка операции жизненного цикла документа.',
    'lifecycle.confirmationActive': 'Уже открыто подтверждение операции жизненного цикла документа.',
    'lifecycle.restoreTitle': 'Восстановить защищённое содержимое?',
    'lifecycle.restoreBody': 'Восстановить контрольную точку {checkpoint} из редакции {revision}? Текущее содержимое останется доступно через обычную отмену в режиме {mode}.',
    'lifecycle.restore': 'Восстановить точку',
    'lifecycle.checkpoint.preMode': 'до смены режима',
    'lifecycle.checkpoint.preReplacement': 'до разрушительной замены',
    'lifecycle.checkpointUnavailable': 'Эта контрольная точка недоступна для статьи.',
    'lifecycle.restoreCancelled': 'Восстановление отменено. Редакция и история не изменены.',
    'lifecycle.restored': 'Контрольная точка восстановлена как редакция {revision}; отмена вернёт заменённое содержимое.',
    'lifecycle.restoreRequiresEditing': 'Вернитесь в исходник или визуальный режим для восстановления точки.',
    'lifecycle.activeModeChanged': 'Активный режим изменился до восстановления контрольной точки.',
    'lifecycle.sourceUnavailable': 'Редактор исходника не готов к восстановлению.',
    'lifecycle.visualUnavailable': 'Визуальный редактор не готов к восстановлению.',
    'lifecycle.recoveryEnvelopeUnavailable': 'Сохранённый пакет восстановления больше недоступен.',
    'lifecycle.recoveryDocumentUnknown': 'Документ восстановления отсутствует в фиксированном каталоге.',
    'lifecycle.openSource': 'Открыть исходник',
    'lifecycle.exportRawMarkdown': 'Экспортировать исходный Markdown',
    'lifecycle.recover': 'Восстановить',
    'mode.group': 'Режим редактора',
    'mode.source': 'Исходник',
    'mode.visual': 'Визуальный',
    'mode.preview': 'Просмотр',
    'mode.surface.source': 'Область редактора исходника',
    'mode.surface.visual': 'Область визуального редактора',
    'mode.surface.preview': 'Область просмотра',
    'language.zh': 'Китайский',
    'language.en': 'Английский',
    'language.ru': 'Русский',
    'theme.default': 'По умолчанию',
    'theme.dark': 'Тёмная',
    'theme.gray': 'Серая',
    'theme.abyss': 'Бездна',
    'theme.green': 'Свежая',
    'theme.red': 'Яркая',
    'theme.violet': 'Мягкая',
    'theme.blue': 'Спокойная',
    'status.sync.failed': 'Синхронизация требует внимания',
    'status.sync.pending': 'Изменения ожидают',
    'status.sync.running': 'Подготовка режима',
    'status.sync.waitingComposition': 'Ожидание завершения ввода',
    'status.sync.synchronized': 'Все изменения синхронизированы',
    'status.sync.unavailable': 'Состояние синхронизации недоступно',
    'status.synchronization': 'Синхронизация: {status}',
    'status.autosave': 'Автосохранение: {status}',
    'status.manualCheckpoint': 'Ручная точка: {status}',
    'status.currentMode': 'Режим: {mode}',
    'status.idle': 'ожидание',
    'status.pending': 'ожидает',
    'status.saving': 'сохранение',
    'status.saved': 'сохранено',
    'status.failed': 'ошибка',
    'status.synchronized': 'синхронизировано',
    'status.dirty': 'изменено',
    'status.clean': 'чисто',
    'status.unavailableFinalPreview': 'Недоступно в итоговом просмотре.',
    'status.unavailableCurrentMode': 'Недоступно в текущем режиме.',
    'status.alignmentUnavailable': 'Выравнивание доступно только для абзацев и блоков H1–H5.',
    'status.manualSaveInProgress': 'Сохраняется ручная контрольная точка.',
    'status.modeChangeInProgress': 'Смена режима уже выполняется.',
    'status.contentCommandsUnavailable': 'Команды редактирования недоступны в итоговом просмотре.',
    'status.selectSourceText': 'Выделите исходный текст перед применением отметки.',
    'status.fullscreenUnavailable': 'Полноэкранный режим недоступен до монтирования интерфейса приложения.',
    'status.lifecycleInProgress': 'Выполняется защищённая операция с документом.',
    'feedback.applied': 'Применено: {command}.',
    'feedback.removed': 'Удалено: {command}.',
    'feedback.inserted': 'Вставлено: {command}.',
    'feedback.noChange': '{command}: без изменений.',
    'feedback.completed': 'Завершено: {command}.',
    'feedback.editorOpened': 'Открыт редактор: {editor}.',
    'feedback.modePreviewOpened': 'Итоговый просмотр открыт.',
    'feedback.modeReturned': 'Возврат в режим {mode}.',
    'feedback.modeChanged': 'Выбран режим {mode}.',
    'feedback.languageChanged': 'Язык интерфейса изменён: {language}.',
    'feedback.themeChanged': 'Тема интерфейса изменена: {theme}.',
    'feedback.themeChangedSessionOnly': 'Тема {theme} включена для этой сессии; хранилище браузера недоступно.',
    'feedback.lineSpacingChanged': 'Межстрочный интервал изменён на {value}.',
    'feedback.lineSpacingChangedSessionOnly': 'Межстрочный интервал изменён на {value} для этой сессии; хранилище браузера недоступно.',
    'feedback.codeCopied': 'Код скопирован.',
    'feedback.codeCopyFailed': 'Не удалось скопировать код. Проверьте разрешение буфера обмена.',
    'feedback.rawNodeUnavailable': 'Узел исходного текста больше не выбран.',
    'feedback.nodeUnavailable': 'Выбранный объект «{kind}» больше недоступен.',
    'feedback.tableInserted': 'Вставлена таблица {size}.',
    'feedback.tableUnavailable': 'Вставка таблицы недоступна.',
    'feedback.shortcutsUpdated': 'Сочетания клавиш обновлены.',
    'feedback.fullscreenEntered': 'Полноэкранный режим включён.',
    'feedback.fullscreenExited': 'Полноэкранный режим выключен.',
    'feedback.externalDetail': 'Ошибка операции: {detail}',
    'feedback.validationDetail': 'Ошибка проверки: {detail}',
    'feedback.fullscreenDetail': 'Ошибка полноэкранного режима: {detail}',
    'feedback.exportDetail': 'Ошибка экспорта: {detail}',
    'feedback.searchDetail': 'Ошибка поиска: {detail}',
    'feedback.statisticsDetail': 'Ошибка статистики: {detail}',
    'feedback.shortcutDetail': 'Ошибка настроек сочетаний: {detail}',
    'feedback.dedicatedEditorDetail': 'Ошибка обновления редактора: {detail}',
    'feedback.dedicated.activeSurfaceRequired': 'Для отдельного редактора требуется активная область редактирования.',
    'feedback.dedicated.planning': 'Приложение не смогло подготовить обновление отдельного редактора. Проверьте черновик и повторите.',
    'feedback.dedicated.revision': 'Редакция документа изменилась до применения. Проверьте содержимое и повторите.',
    'feedback.dedicated.staleSelection': 'Выделение изменилось до применения. Откройте цель снова или проверьте черновик.',
    'feedback.dedicated.transaction': 'Транзакция отдельного редактора отклонена. Проверьте черновик и повторите.',
    'feedback.dedicated.formulaContextUnavailable': 'Контекст редактирования формулы недоступен. Откройте выбор формулы снова.',
    'feedback.dedicated.sourceFormulaUnavailable': 'Редактор исходника недоступен. Проверьте формулу и повторите.',
    'feedback.dedicated.visualFormulaUnavailable': 'Визуальный редактор недоступен. Проверьте формулу и повторите.',
    'feedback.dedicated.staleFormulaSelection': 'Выделение изменилось до применения. Откройте цель снова или проверьте формулу.',
    'feedback.dedicated.formulaUnavailable': 'Выбранная формула больше недоступна для обновления. Проверьте формулу.',
    'feedback.dedicated.codeContextUnavailable': 'Контекст редактирования блока кода недоступен. Откройте редактор снова.',
    'feedback.dedicated.sourceDraftUnavailable': 'Редактор исходника недоступен. Проверьте черновик и повторите.',
    'feedback.dedicated.visualDraftUnavailable': 'Визуальный редактор недоступен. Проверьте черновик и повторите.',
    'feedback.dedicated.codeUnavailable': 'Выбранный блок кода больше недоступен для обновления. Проверьте черновик.',
    'feedback.dedicated.panelContextUnavailable': 'Контекст редактирования панели недоступен. Откройте редактор снова.',
    'feedback.dedicated.panelCommandUnavailable': 'Команда панели больше недоступна. Откройте редактор снова.',
    'feedback.dedicated.panelUnavailable': 'Выбранная панель больше недоступна для обновления. Проверьте черновик.',
    'validation.panelSource': 'Введите полный исходник «{panel}» с заголовком и содержимым.',
    'validation.panelCommand': 'Выбранная команда панели недоступна.',
    'validation.columnLayoutSource': 'Введите полный исходник «{layout}» со всеми обязательными колонками.',
    'validation.disclosureSource': 'Введите корректный исходник «{layout}» со всеми обязательными именованными разделами.',
    'validation.timelineSource': 'Введите корректный исходник «{timeline}» с заголовком и хотя бы одним элементом.',
    'validation.invalidDraft': 'Черновик недействителен для этого редактора.',
    'export.markdownDownloaded': 'Редакция Markdown {revision} загружена.',
    'export.renderedDownloaded': 'Редакция {format} {revision} загружена.',
    'export.pdfDownloaded': 'Редакция PDF {revision} загружена.',
    'export.pdfDownloadedWithOmittedRemoteImages': 'Редакция PDF {revision} загружена; удалённых изображений не встроено: {count}.',
    'export.screenshotDownloaded': 'Длинный снимок редакции {revision} загружен.',
    'export.screenshotDownloadedWithOmittedRemoteImages': 'Длинный снимок редакции {revision} загружен; удалённых изображений не встроено: {count}.',
    'export.rawRecoveryExported': 'Исходные данные восстановления экспортированы.',
  } satisfies Record<keyof typeof APP_EN_MESSAGES, string>),
})

const EN_MESSAGES = {
  ...APP_MESSAGES.en,
  'common.apply': 'Apply',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.copy': 'Copy',
  'common.edit': 'Edit',
  'common.retry': 'Retry',
  'common.keepEditing': 'Keep editing',
  'common.discardChanges': 'Discard changes',
  'search.resultCount': 'Result {current} of {total}',
  'source.markdownSource': 'Markdown source',
  'source.selectionActions': 'Source selection actions',
  'source.quoteSelected': 'Quote selected source',
  'source.quote': 'Quote',
  'source.testControl': 'Markdown source test control',
  'preview.codeActions': 'Code block actions',
  'preview.copyCode': 'Copy code',
  'preview.editCode': 'Edit code',
  'preview.taskCheckbox': 'Task item checkbox for {label}',
  'preview.taskCompleted': 'Completed task: {label}',
  'preview.taskIncomplete': 'Incomplete task: {label}',
  'preview.collapseCode': 'Fold code',
  'preview.expandCode': 'Expand code',
  'preview.collapse': 'Fold',
  'preview.expand': 'Expand',
  'formula.kicker': 'Formula',
  'formula.title': 'Insert formula',
  'formula.mode': 'Formula mode',
  'formula.inline': 'Inline formula',
  'formula.block': 'Block formula',
  'formula.toolSections': 'Formula tool sections',
  'formula.quickTools': 'Quick tools',
  'formula.templates': 'Formula templates',
  'formula.textStyles': 'Text styles',
  'formula.symbolCategories': 'Formula symbol categories',
  'formula.commonSymbols': 'Common symbols',
  'formula.rootsIndices': 'Roots and indices',
  'formula.limitsLogarithms': 'Limits and logarithms',
  'formula.trigonometry': 'Trigonometry',
  'formula.fractionTemplate': 'Fraction template',
  'formula.fraction': 'Fraction',
  'formula.pythagoreanTemplate': 'Pythagorean theorem template',
  'formula.pythagorean': 'Pythagorean theorem',
  'formula.summationSymbol': 'Summation symbol',
  'formula.summation': 'Summation',
  'formula.squareRoot': 'Square root',
  'formula.nthRoot': 'Nth root',
  'formula.superscriptTool': 'Superscript',
  'formula.subscriptTool': 'Subscript',
  'formula.limit': 'Limit',
  'formula.logarithm': 'Logarithm',
  'formula.naturalLogarithm': 'Natural logarithm',
  'formula.sine': 'Sine',
  'formula.cosine': 'Cosine',
  'formula.tangent': 'Tangent',
  'formula.quadratic': 'Quadratic formula',
  'formula.integral': 'Definite integral',
  'formula.matrix': 'Matrix',
  'formula.boldText': 'Bold math text',
  'formula.romanText': 'Roman text',
  'formula.italicText': 'Italic math text',
  'formula.preview': 'Live preview',
  'formula.source': 'Formula source',
  'formula.renderedInline': 'Rendered inline formula',
  'formula.renderedBlock': 'Rendered block formula',
  'formula.previewUnavailable': 'Formula preview unavailable.',
  'formula.previewUnavailableWithDetail': 'Formula preview unavailable: {detail}',
  'formula.previewError': 'Formula preview error',
  'toc.title': 'Table of contents',
  'toc.empty': 'No headings yet.',
  'toc.navigation': 'Table of contents',
  'toc.inserted': 'Table of contents inserted.',
  'toc.alreadyExists': 'Table of contents already exists.',
  'blockMenu.addBlock': 'Add block',
  'blockMenu.openActions': 'Open block actions',
  'blockMenu.actions': 'Block actions',
  'blockMenu.text': 'Text',
  'blockMenu.codeBlock': 'Code Block',
  'blockMenu.image': 'image',
  'blockMenu.color': 'Color',
  'blockMenu.turnInto': 'Turn into',
  'blockMenu.resetFormatting': 'Reset formatting',
  'blockMenu.downloadImage': 'Download image',
  'blockMenu.duplicateNode': 'Duplicate node',
  'blockMenu.copyClipboard': 'Copy to clipboard',
  'blockMenu.copyFailed': 'Copy failed. Select the text and use your browser’s Copy command.',
  'blockMenu.copyAnchor': 'Copy anchor link',
  'blockMenu.delete': 'Delete',
  'blockMenu.heading1': 'Heading 1',
  'blockMenu.heading2': 'Heading 2',
  'blockMenu.heading3': 'Heading 3',
  'blockMenu.quote': 'Quote',
  'blockMenu.recentColors': 'Recent colors',
  'blockMenu.textColor': 'Text color',
  'blockMenu.backgroundColor': 'Background color',
  'blockMenu.colorText': '{color} text',
  'blockMenu.colorBackground': '{color} background',
  'blockMenu.color.default': 'Default',
  'blockMenu.color.gray': 'Gray',
  'blockMenu.color.brown': 'Brown',
  'blockMenu.color.orange': 'Orange',
  'blockMenu.color.yellow': 'Yellow',
  'blockMenu.color.green': 'Green',
  'blockMenu.color.blue': 'Blue',
  'blockMenu.color.purple': 'Purple',
  'blockMenu.color.pink': 'Pink',
  'blockMenu.color.red': 'Red',
  'blockMenu.addAbove': 'Add above',
  'blockMenu.addBelow': 'Add below',
  'codeNode.editable': 'Editable code block',
  'codeNode.actions': 'Code block actions',
  'codeNode.changeLanguage': 'Change language',
  'codeNode.copy': 'Copy',
  'codeNode.copied': 'Copied',
  'codeNode.copyCode': 'Copy code',
  'codeNode.advanced': 'Edit',
  'codeNode.editCode': 'Advanced code editor',
  'codeNode.fold': 'Fold',
  'codeNode.expand': 'Expand',
  'codeNode.foldCode': 'Fold code',
  'codeNode.expandCode': 'Expand code',
  'codeNode.previewError': 'Code preview error',
  'codeNode.plainText': 'Plain text',
  'semanticNode.copySource': 'Copy source',
  'semanticNode.editChart': 'Edit chart',
  'semanticNode.editChartLabel': 'Edit chart: {label}',
  'semanticNode.editSource': 'Edit source',
  'semanticNode.editSourceLabel': 'Edit source: {label}',
  'semanticNode.content': 'Content',
  'semanticNode.timeline': 'Timeline',
  'semanticNode.tabs': 'Tabs',
  'semanticNode.accordion': 'Accordion',
  'semanticNode.columns': 'Columns',
  'semanticNode.twoColumnLayout': 'Two-column layout',
  'semanticNode.multiColumnLayout': 'Multi-column layout',
  'semanticNode.panel.primary': 'Primary panel',
  'semanticNode.panel.info': 'Info panel',
  'semanticNode.panel.success': 'Success panel',
  'semanticNode.panel.warning': 'Warning panel',
  'semanticNode.panel.danger': 'Danger panel',
  'semanticNode.columnRegion': 'Column {number} of {total}',
  'semanticNode.chartTitle': '{type} chart',
  'semanticNode.chartData': '{title} data',
  'semanticNode.series': 'Series',
  'semanticNode.mermaidDiagram': 'Mermaid diagram',
  'semanticNode.mermaidIdentity': '{type} Mermaid',
  'semanticNode.previewUnavailable': '{kind} preview unavailable',
  'semanticNode.browserCannotPreview': 'Your browser cannot preview this {kind}.',
  'semanticNode.mediaIdentity': '{kind} · {name}',
  'semanticNode.attachmentIdentity': '{kind} · {name}',
  'semanticNode.drawioIdentity': 'draw.io diagram · {name}',
  'semanticNode.attachment.pdf': 'PDF',
  'semanticNode.attachment.word': 'Word document',
  'semanticNode.attachment.file': 'File',
  'semanticNode.attachmentBytes': '{size} bytes',
  'semanticNode.attachmentSizeUnknown': 'size not reported',
  'semanticNode.openAttachment': 'Open {name}',
  'semanticNode.mermaidPreviewFailed': 'Mermaid preview failed: {message}',
  'semanticNode.unknownMermaidError': 'Unknown Mermaid rendering error.',
  'semanticNode.chartPreviewFailed': 'Chart preview failed: {message}',
  'semanticNode.unknownChartError': 'Unknown chart rendering error.',
  'tableNode.editable': 'Editable Markdown table',
  'tableNode.rowActions': 'Row {number} actions',
  'tableNode.columnActions': 'Column {number} actions',
  'tableNode.addRowBefore': 'Add row before',
  'tableNode.addRowAfter': 'Add row after',
  'tableNode.duplicateRow': 'Duplicate row',
  'tableNode.moveRowUp': 'Move row up',
  'tableNode.moveRowDown': 'Move row down',
  'tableNode.deleteRow': 'Delete row',
  'tableNode.addColumnBefore': 'Add column before',
  'tableNode.addColumnAfter': 'Add column after',
  'tableNode.duplicateColumn': 'Duplicate column',
  'tableNode.moveColumnLeft': 'Move column left',
  'tableNode.moveColumnRight': 'Move column right',
  'tableNode.deleteColumn': 'Delete column',
  'tableNode.alignColumnLeft': 'Align column left',
  'tableNode.alignColumnCenter': 'Align column center',
  'tableNode.alignColumnRight': 'Align column right',
  'tableNode.sortAscending': 'Sort ascending',
  'tableNode.sortDescending': 'Sort descending',
  'tableNode.mergeCellsUnavailable': 'Merge cells unavailable',
  'tableNode.splitCellUnavailable': 'Split cell unavailable',
  'tableNode.backgroundColorUnavailable': 'Background color unavailable',
  'tableNode.verticalAlignmentUnavailable': 'Vertical alignment unavailable',
  'tableNode.persistentWidthUnavailable': 'Persistent width unavailable',
  'tableNode.persistentSortUnavailable': 'Persistent sort unavailable',
  'rawNode.unknownInline': 'Unknown inline source',
  'rawNode.unknownBlock': 'Unknown block source',
  'rawNode.editSource': 'Edit source',
  'rawNode.editUnknownInline': 'Edit unknown inline source',
  'rawNode.editUnknownBlock': 'Edit unknown block source',
  'chartEditor.kicker': 'Chart-table semantic editor',
  'chartEditor.title': 'Edit chart table',
  'chartEditor.type': 'Chart type',
  'chartEditor.titleLabel': 'Title',
  'chartEditor.series': 'Series',
  'chartEditor.column': 'Column {number}',
  'chartEditor.cell': 'Row {row}, cell {cell}',
  'chartEditor.livePreview': 'Live chart preview',
  'chartEditor.previewUnavailable': 'Chart preview unavailable: {message}',
  'chartEditor.discardTitle': 'Discard chart-table changes?',
  'chartEditor.unchanged': 'The document has not changed.',
  'codeEditor.kicker': 'Local source editor',
  'codeEditor.title': 'Code block',
  'codeEditor.source': 'Source',
  'codeEditor.language': 'Language',
  'codeEditor.discardTitle': 'Discard local source changes?',
  'codeEditor.dirtyExplanation': 'This draft has unapplied changes.',
  'draftEditor.kicker': 'Semantic editor',
  'draftEditor.discardTitle': 'Discard unsaved draft?',
  'draftEditor.unchangedExplanation': 'Your document has not changed. Keep editing or discard this detached draft.',
  'drawio.dialogLabel': 'draw.io diagram editor',
  'drawio.kicker': 'Controlled integration',
  'drawio.title': 'draw.io diagram',
  'drawio.cancelLabel': 'Cancel draw.io editing',
  'drawio.iframeTitle': 'W-Editor draw.io bridge',
  'drawio.status.loading': 'Loading secure draw.io bridge…',
  'drawio.status.connecting': 'Connecting to the local draw.io editor…',
  'drawio.status.ready': 'Diagram editor ready',
  'drawio.status.saving': 'Rendering and applying diagram…',
  'drawio.status.unavailable': 'The draw.io resources could not be loaded. Close this dialog and retry.',
  'media.kicker': 'Media',
  'media.heading': '{kind} asset',
  'media.name': 'Name',
  'media.url': 'URL',
  'media.localFile': 'Or select a local {kind} file',
  'media.uploading': 'Uploading through the configured adapter…',
  'media.uploadReady': '{mediaType} · {size} bytes · URL ready',
  'media.nameRequired': 'Asset name is required.',
  'media.nameInvalid': 'Asset name cannot contain a closing bracket or line break.',
  'media.urlRequired': 'Asset URL is required.',
  'media.urlUnsupported': 'Asset URL must be an absolute HTTP or HTTPS URL.',
  'media.urlCredentials': 'Asset URL must not contain credentials.',
  'media.uploadCancelled': 'Upload cancelled. The document was not changed.',
  'media.uploadFailed': 'Upload failed. The document was not changed.',
  'media.kind.audio': 'Audio',
  'media.kind.file': 'File',
  'media.kind.image': 'Image',
    'image.width': 'Width',
    'image.height': 'Height',
    'image.lockAspectRatio': 'Lock aspect ratio',
    'image.resetSize': 'Original size',
    'image.edit': 'Edit image',
    'image.dimensions': 'Image dimensions',

  'media.kind.pdf': 'PDF',
  'media.kind.video': 'Video',
  'media.kind.word': 'Word document',
} as const

export type UiMessageKey = keyof typeof EN_MESSAGES
export type UiMessageParams = Readonly<Record<string, string | number>>

export interface UiLocalizationStore {
  readonly locale: UiLocale
  setLocale(locale: UiLocale): void
  subscribe(listener: (locale: UiLocale) => void): () => void
  t(key: UiMessageKey, params?: UiMessageParams): string
}

const UI_MESSAGES = Object.freeze({
  zh: Object.freeze({
    ...APP_MESSAGES.zh,
    'common.apply': '应用',
    'common.cancel': '取消',
    'common.close': '关闭',
    'common.copy': '复制',
    'common.edit': '编辑',
    'common.retry': '重试',
    'common.keepEditing': '继续编辑',
    'common.discardChanges': '放弃更改',
    'search.resultCount': '第 {current} 项，共 {total} 项',
    'source.markdownSource': 'Markdown 源码',
    'source.selectionActions': '源码选择操作',
    'source.quoteSelected': '引用所选源码',
    'source.quote': '引用',
    'source.testControl': 'Markdown 源码测试控件',
    'preview.codeActions': '代码块操作',
    'preview.copyCode': '复制代码',
    'preview.editCode': '编辑代码',
    'preview.taskCheckbox': '任务项复选框：{label}',
    'preview.taskCompleted': '已完成任务：{label}',
    'preview.taskIncomplete': '未完成任务：{label}',
    'preview.collapseCode': '折叠代码',
    'preview.expandCode': '展开代码',
    'preview.collapse': '折叠',
    'preview.expand': '展开',
    'formula.kicker': '公式',
    'formula.title': '插入公式',
    'formula.mode': '公式模式',
    'formula.inline': '行内公式',
    'formula.block': '块级公式',
    'formula.toolSections': '公式工具分区',
    'formula.quickTools': '快捷工具',
    'formula.templates': '公式模板',
    'formula.textStyles': '文本样式',
    'formula.symbolCategories': '公式符号分类',
    'formula.commonSymbols': '常用符号',
    'formula.rootsIndices': '根式与上下标',
    'formula.limitsLogarithms': '极限与对数',
    'formula.trigonometry': '三角函数',
    'formula.fractionTemplate': '分数模板',
    'formula.fraction': '分数',
    'formula.pythagoreanTemplate': '勾股定理模板',
    'formula.pythagorean': '勾股定理',
    'formula.summationSymbol': '求和符号',
    'formula.summation': '求和',
    'formula.squareRoot': '平方根',
    'formula.nthRoot': 'n 次根',
    'formula.superscriptTool': '上标',
    'formula.subscriptTool': '下标',
    'formula.limit': '极限',
    'formula.logarithm': '对数',
    'formula.naturalLogarithm': '自然对数',
    'formula.sine': '正弦',
    'formula.cosine': '余弦',
    'formula.tangent': '正切',
    'formula.quadratic': '一元二次方程求根公式',
    'formula.integral': '定积分',
    'formula.matrix': '矩阵',
    'formula.boldText': '粗体数学文本',
    'formula.romanText': '正体文本',
    'formula.italicText': '斜体数学文本',
    'formula.preview': '实时预览',
    'formula.source': '公式源码',
    'formula.renderedInline': '已渲染的行内公式',
    'formula.renderedBlock': '已渲染的块级公式',
    'formula.previewUnavailable': '公式预览不可用。',
    'formula.previewUnavailableWithDetail': '公式预览不可用：{detail}',
    'formula.previewError': '公式预览错误',
    'toc.title': '目录',
    'toc.empty': '暂无标题。',
    'toc.navigation': '目录',
    'toc.inserted': '已插入目录。',
    'toc.alreadyExists': '目录已存在。',
    'blockMenu.addBlock': '添加行',
    'blockMenu.openActions': '打开块操作',
    'blockMenu.actions': '块操作',
    'blockMenu.text': '文本',
    'blockMenu.codeBlock': '代码块',
    'blockMenu.image': '图片',
    'blockMenu.color': '颜色',
    'blockMenu.turnInto': '转换为',
    'blockMenu.resetFormatting': '重置格式',
    'blockMenu.downloadImage': '下载图片',
    'blockMenu.duplicateNode': '复制节点',
    'blockMenu.copyClipboard': '复制到剪贴板',
    'blockMenu.copyFailed': '复制失败，请选中文字后使用浏览器的复制功能。',
    'blockMenu.copyAnchor': '复制锚点链接',
    'blockMenu.delete': '删除',
    'blockMenu.heading1': '一级标题',
    'blockMenu.heading2': '二级标题',
    'blockMenu.heading3': '三级标题',
    'blockMenu.quote': '引用',
    'blockMenu.recentColors': '最近使用颜色',
    'blockMenu.textColor': '文字颜色',
    'blockMenu.backgroundColor': '背景颜色',
    'blockMenu.colorText': '{color}文字',
    'blockMenu.colorBackground': '{color}背景',
    'blockMenu.color.default': '默认',
    'blockMenu.color.gray': '灰色',
    'blockMenu.color.brown': '棕色',
    'blockMenu.color.orange': '橙色',
    'blockMenu.color.yellow': '黄色',
    'blockMenu.color.green': '绿色',
    'blockMenu.color.blue': '蓝色',
    'blockMenu.color.purple': '紫色',
    'blockMenu.color.pink': '粉色',
    'blockMenu.color.red': '红色',
    'blockMenu.addAbove': '上方添加行',
    'blockMenu.addBelow': '下方添加行',
    'codeNode.editable': '可编辑代码块',
    'codeNode.actions': '代码块操作',
    'codeNode.changeLanguage': '更改语言',
    'codeNode.copy': '复制',
    'codeNode.copied': '已复制',
    'codeNode.copyCode': '复制代码',
    'codeNode.advanced': '编辑',
    'codeNode.editCode': '高级代码编辑器',
    'codeNode.fold': '折叠',
    'codeNode.expand': '展开',
    'codeNode.foldCode': '折叠代码',
    'codeNode.expandCode': '展开代码',
    'codeNode.previewError': '代码预览错误',
    'codeNode.plainText': '纯文本',
    'semanticNode.copySource': '复制源码',
    'semanticNode.editChart': '编辑图表',
    'semanticNode.editChartLabel': '编辑图表：{label}',
    'semanticNode.editSource': '编辑源码',
    'semanticNode.editSourceLabel': '编辑源码：{label}',
    'semanticNode.content': '内容',
    'semanticNode.timeline': '时间线',
    'semanticNode.tabs': '标签页',
    'semanticNode.accordion': '手风琴',
    'semanticNode.columns': '分栏',
    'semanticNode.twoColumnLayout': '双栏布局',
    'semanticNode.multiColumnLayout': '多栏布局',
    'semanticNode.panel.primary': '主要面板',
    'semanticNode.panel.info': '信息面板',
    'semanticNode.panel.success': '成功面板',
    'semanticNode.panel.warning': '警告面板',
    'semanticNode.panel.danger': '危险面板',
    'semanticNode.columnRegion': '第 {number} 列，共 {total} 列',
    'semanticNode.chartTitle': '{type}图表',
    'semanticNode.chartData': '{title}数据',
    'semanticNode.series': '系列',
    'semanticNode.mermaidDiagram': 'Mermaid 图表',
    'semanticNode.mermaidIdentity': '{type} Mermaid',
    'semanticNode.previewUnavailable': '{kind}预览不可用',
    'semanticNode.browserCannotPreview': '浏览器无法预览此{kind}。',
    'semanticNode.mediaIdentity': '{kind} · {name}',
    'semanticNode.attachmentIdentity': '{kind} · {name}',
    'semanticNode.drawioIdentity': 'draw.io 图表 · {name}',
    'semanticNode.attachment.pdf': 'PDF',
    'semanticNode.attachment.word': 'Word 文档',
    'semanticNode.attachment.file': '文件',
    'semanticNode.attachmentBytes': '{size} 字节',
    'semanticNode.attachmentSizeUnknown': '未报告大小',
    'semanticNode.openAttachment': '打开 {name}',
    'semanticNode.mermaidPreviewFailed': 'Mermaid 预览失败：{message}',
    'semanticNode.unknownMermaidError': '未知 Mermaid 渲染错误。',
    'semanticNode.chartPreviewFailed': '图表预览失败：{message}',
    'semanticNode.unknownChartError': '未知图表渲染错误。',
    'tableNode.editable': '可编辑 Markdown 表格',
    'tableNode.rowActions': '第 {number} 行操作',
    'tableNode.columnActions': '第 {number} 列操作',
    'tableNode.addRowBefore': '在前面添加行',
    'tableNode.addRowAfter': '在下方添加行',
    'tableNode.duplicateRow': '复制行',
    'tableNode.moveRowUp': '上移行',
    'tableNode.moveRowDown': '下移行',
    'tableNode.deleteRow': '删除行',
    'tableNode.addColumnBefore': '在前面添加列',
    'tableNode.addColumnAfter': '在右侧添加列',
    'tableNode.duplicateColumn': '复制列',
    'tableNode.moveColumnLeft': '左移列',
    'tableNode.moveColumnRight': '右移列',
    'tableNode.deleteColumn': '删除列',
    'tableNode.alignColumnLeft': '列左对齐',
    'tableNode.alignColumnCenter': '列居中对齐',
    'tableNode.alignColumnRight': '列右对齐',
    'tableNode.sortAscending': '升序排序',
    'tableNode.sortDescending': '降序排序',
    'tableNode.mergeCellsUnavailable': '合并单元格不可用',
    'tableNode.splitCellUnavailable': '拆分单元格不可用',
    'tableNode.backgroundColorUnavailable': '单元格背景色不可用',
    'tableNode.verticalAlignmentUnavailable': '垂直对齐不可用',
    'tableNode.persistentWidthUnavailable': '持久列宽不可用',
    'tableNode.persistentSortUnavailable': '持久排序不可用',
    'rawNode.unknownInline': '未知行内源码',
    'rawNode.unknownBlock': '未知块源码',
    'rawNode.editSource': '编辑源码',
    'rawNode.editUnknownInline': '编辑未知行内源码',
    'rawNode.editUnknownBlock': '编辑未知块源码',
    'chartEditor.kicker': '图表表格语义编辑器',
    'chartEditor.title': '编辑图表表格',
    'chartEditor.type': '图表类型',
    'chartEditor.titleLabel': '标题',
    'chartEditor.series': '系列',
    'chartEditor.column': '第 {number} 列',
    'chartEditor.cell': '第 {row} 行，第 {cell} 个单元格',
    'chartEditor.livePreview': '实时图表预览',
    'chartEditor.previewUnavailable': '图表预览暂不可用：{message}',
    'chartEditor.discardTitle': '放弃图表表格更改？',
    'chartEditor.unchanged': '文档尚未更改。',
    'codeEditor.kicker': '源码编辑器',
    'codeEditor.title': '代码块',
    'codeEditor.source': '源码',
    'codeEditor.language': '语言',
    'codeEditor.discardTitle': '放弃本地源码更改？',
    'codeEditor.dirtyExplanation': '此草稿包含尚未应用的更改。',
    'draftEditor.kicker': '语义编辑器',
    'draftEditor.discardTitle': '放弃未保存的草稿？',
    'draftEditor.unchangedExplanation': '文档尚未更改。你可以继续编辑或放弃此独立草稿。',
    'drawio.dialogLabel': 'draw.io 图表编辑器',
    'drawio.kicker': '受控集成',
    'drawio.title': 'draw.io 图表',
    'drawio.cancelLabel': '取消 draw.io 编辑',
    'drawio.iframeTitle': 'W-Editor draw.io 桥接器',
    'drawio.status.loading': '正在加载安全的 draw.io 桥接器…',
    'drawio.status.connecting': '正在连接本地 draw.io 编辑器…',
    'drawio.status.ready': '图表编辑器已就绪',
    'drawio.status.saving': '正在渲染并应用图表…',
    'drawio.status.unavailable': 'draw.io 资源或 CSP 加载失败。关闭此对话框后可重试。',
    'media.kicker': '媒体',
    'media.heading': '{kind}资源',
    'media.name': '名称',
    'media.url': 'URL',
    'media.localFile': '或选择本地{kind}文件',
    'media.uploading': '正在通过已配置的适配器上传…',
    'media.uploadReady': '{mediaType} · {size} 字节 · URL 已就绪',
    'media.nameRequired': '资源名称为必填项。',
    'media.nameInvalid': '资源名称不能包含右方括号或换行符。',
    'media.urlRequired': '资源 URL 为必填项。',
    'media.urlUnsupported': '资源 URL 必须是绝对 HTTP 或 HTTPS 地址。',
    'media.urlCredentials': '资源 URL 不能包含凭据。',
    'media.uploadCancelled': '上传已取消，文档未更改。',
    'media.uploadFailed': '上传失败，文档未更改。',
    'media.kind.audio': '音频',
    'media.kind.file': '文件',
    'media.kind.image': '图片',
    'image.width': '宽度',
    'image.height': '高度',
    'image.lockAspectRatio': '锁定比例',
    'image.resetSize': '原始尺寸',
    'image.edit': '编辑图片',
    'image.dimensions': '图片尺寸',

    'media.kind.pdf': 'PDF',
    'media.kind.video': '视频',
    'media.kind.word': 'Word 文档',
  }),
  en: Object.freeze(EN_MESSAGES),
  ru: Object.freeze({
    ...APP_MESSAGES.ru,
    'common.apply': 'Применить',
    'common.cancel': 'Отмена',
    'common.close': 'Закрыть',
    'common.copy': 'Копировать',
    'common.edit': 'Редактировать',
    'common.retry': 'Повторить',
    'common.keepEditing': 'Продолжить редактирование',
    'common.discardChanges': 'Отменить изменения',
    'search.resultCount': 'Результат {current} из {total}',
    'source.markdownSource': 'Исходный Markdown',
    'source.selectionActions': 'Действия с выделением исходного текста',
    'source.quoteSelected': 'Цитировать выделенный исходный текст',
    'source.quote': 'Цитата',
    'source.testControl': 'Тестовый элемент исходного Markdown',
    'preview.codeActions': 'Действия с блоком кода',
    'preview.copyCode': 'Копировать код',
    'preview.editCode': 'Редактировать код',
    'preview.taskCheckbox': 'Флажок задачи: {label}',
    'preview.taskCompleted': 'Выполненная задача: {label}',
    'preview.taskIncomplete': 'Невыполненная задача: {label}',
    'preview.collapseCode': 'Свернуть код',
    'preview.expandCode': 'Развернуть код',
    'preview.collapse': 'Свернуть',
    'preview.expand': 'Развернуть',
    'formula.kicker': 'Формула',
    'formula.title': 'Вставить формулу',
    'formula.mode': 'Режим формулы',
    'formula.inline': 'Встроенная формула',
    'formula.block': 'Блочная формула',
    'formula.toolSections': 'Разделы инструментов формул',
    'formula.quickTools': 'Быстрые инструменты',
    'formula.templates': 'Шаблоны формул',
    'formula.textStyles': 'Стили текста',
    'formula.symbolCategories': 'Категории символов формул',
    'formula.commonSymbols': 'Основные символы',
    'formula.rootsIndices': 'Корни и индексы',
    'formula.limitsLogarithms': 'Пределы и логарифмы',
    'formula.trigonometry': 'Тригонометрия',
    'formula.fractionTemplate': 'Шаблон дроби',
    'formula.fraction': 'Дробь',
    'formula.pythagoreanTemplate': 'Шаблон теоремы Пифагора',
    'formula.pythagorean': 'Теорема Пифагора',
    'formula.summationSymbol': 'Символ суммирования',
    'formula.summation': 'Суммирование',
    'formula.squareRoot': 'Квадратный корень',
    'formula.nthRoot': 'Корень n-й степени',
    'formula.superscriptTool': 'Верхний индекс',
    'formula.subscriptTool': 'Нижний индекс',
    'formula.limit': 'Предел',
    'formula.logarithm': 'Логарифм',
    'formula.naturalLogarithm': 'Натуральный логарифм',
    'formula.sine': 'Синус',
    'formula.cosine': 'Косинус',
    'formula.tangent': 'Тангенс',
    'formula.quadratic': 'Квадратная формула',
    'formula.integral': 'Определённый интеграл',
    'formula.matrix': 'Матрица',
    'formula.boldText': 'Полужирный математический текст',
    'formula.romanText': 'Прямой текст',
    'formula.italicText': 'Курсивный математический текст',
    'formula.preview': 'Предпросмотр',
    'formula.source': 'Исходный код формулы',
    'formula.renderedInline': 'Отображённая встроенная формула',
    'formula.renderedBlock': 'Отрисованная блочная формула',
    'formula.previewUnavailable': 'Предпросмотр формулы недоступен.',
    'formula.previewUnavailableWithDetail': 'Предпросмотр формулы недоступен: {detail}',
    'formula.previewError': 'Ошибка предпросмотра формулы',
    'toc.title': 'Оглавление',
    'toc.empty': 'Заголовков пока нет.',
    'toc.navigation': 'Оглавление',
    'toc.inserted': 'Оглавление вставлено.',
    'toc.alreadyExists': 'Оглавление уже существует.',
    'blockMenu.addBlock': 'Добавить блок',
    'blockMenu.openActions': 'Открыть действия с блоком',
    'blockMenu.actions': 'Действия с блоком',
    'blockMenu.text': 'Текст',
    'blockMenu.codeBlock': 'Блок кода',
    'blockMenu.image': 'Изображение',
    'blockMenu.color': 'Цвет',
    'blockMenu.turnInto': 'Преобразовать',
    'blockMenu.resetFormatting': 'Сбросить форматирование',
    'blockMenu.downloadImage': 'Скачать изображение',
    'blockMenu.duplicateNode': 'Дублировать узел',
    'blockMenu.copyClipboard': 'Копировать в буфер обмена',
    'blockMenu.copyFailed': 'Не удалось скопировать. Выделите текст и используйте команду копирования браузера.',
    'blockMenu.copyAnchor': 'Копировать ссылку-якорь',
    'blockMenu.delete': 'Удалить',
    'blockMenu.heading1': 'Заголовок 1',
    'blockMenu.heading2': 'Заголовок 2',
    'blockMenu.heading3': 'Заголовок 3',
    'blockMenu.quote': 'Цитата',
    'blockMenu.recentColors': 'Недавние цвета',
    'blockMenu.textColor': 'Цвет текста',
    'blockMenu.backgroundColor': 'Цвет фона',
    'blockMenu.colorText': '{color} — текст',
    'blockMenu.colorBackground': '{color} — фон',
    'blockMenu.color.default': 'По умолчанию',
    'blockMenu.color.gray': 'Серый',
    'blockMenu.color.brown': 'Коричневый',
    'blockMenu.color.orange': 'Оранжевый',
    'blockMenu.color.yellow': 'Жёлтый',
    'blockMenu.color.green': 'Зелёный',
    'blockMenu.color.blue': 'Синий',
    'blockMenu.color.purple': 'Фиолетовый',
    'blockMenu.color.pink': 'Розовый',
    'blockMenu.color.red': 'Красный',
    'blockMenu.addAbove': 'Добавить выше',
    'blockMenu.addBelow': 'Добавить ниже',
    'codeNode.editable': 'Редактируемый блок кода',
    'codeNode.actions': 'Действия с блоком кода',
    'codeNode.changeLanguage': 'Изменить язык',
    'codeNode.copy': 'Копировать',
    'codeNode.copied': 'Скопировано',
    'codeNode.copyCode': 'Копировать код',
    'codeNode.advanced': 'Редактировать',
    'codeNode.editCode': 'Расширенный редактор кода',
    'codeNode.fold': 'Свернуть',
    'codeNode.expand': 'Развернуть',
    'codeNode.foldCode': 'Свернуть код',
    'codeNode.expandCode': 'Развернуть код',
    'codeNode.previewError': 'Ошибка предпросмотра кода',
    'codeNode.plainText': 'Обычный текст',
    'semanticNode.copySource': 'Копировать исходный текст',
    'semanticNode.editChart': 'Редактировать диаграмму',
    'semanticNode.editChartLabel': 'Редактировать диаграмму: {label}',
    'semanticNode.editSource': 'Редактировать исходный текст',
    'semanticNode.editSourceLabel': 'Редактировать исходный текст: {label}',
    'semanticNode.content': 'Содержимое',
    'semanticNode.timeline': 'Временная шкала',
    'semanticNode.tabs': 'Вкладки',
    'semanticNode.accordion': 'Аккордеон',
    'semanticNode.columns': 'Столбцы',
    'semanticNode.twoColumnLayout': 'Двухколоночный макет',
    'semanticNode.multiColumnLayout': 'Многоколоночный макет',
    'semanticNode.panel.primary': 'Основная панель',
    'semanticNode.panel.info': 'Информационная панель',
    'semanticNode.panel.success': 'Панель успеха',
    'semanticNode.panel.warning': 'Панель предупреждения',
    'semanticNode.panel.danger': 'Панель опасности',
    'semanticNode.columnRegion': 'Столбец {number} из {total}',
    'semanticNode.chartTitle': 'Диаграмма: {type}',
    'semanticNode.chartData': 'Данные «{title}»',
    'semanticNode.series': 'Ряд',
    'semanticNode.mermaidDiagram': 'Диаграмма Mermaid',
    'semanticNode.mermaidIdentity': '{type} Mermaid',
    'semanticNode.previewUnavailable': 'Предпросмотр «{kind}» недоступен',
    'semanticNode.browserCannotPreview': 'Браузер не может показать предпросмотр: {kind}.',
    'semanticNode.mediaIdentity': '{kind} · {name}',
    'semanticNode.attachmentIdentity': '{kind} · {name}',
    'semanticNode.drawioIdentity': 'Диаграмма draw.io · {name}',
    'semanticNode.attachment.pdf': 'PDF',
    'semanticNode.attachment.word': 'Документ Word',
    'semanticNode.attachment.file': 'Файл',
    'semanticNode.attachmentBytes': '{size} байт',
    'semanticNode.attachmentSizeUnknown': 'размер не указан',
    'semanticNode.openAttachment': 'Открыть {name}',
    'semanticNode.mermaidPreviewFailed': 'Ошибка предпросмотра Mermaid: {message}',
    'semanticNode.unknownMermaidError': 'Неизвестная ошибка отрисовки Mermaid.',
    'semanticNode.chartPreviewFailed': 'Ошибка предпросмотра диаграммы: {message}',
    'semanticNode.unknownChartError': 'Неизвестная ошибка отрисовки диаграммы.',
    'tableNode.editable': 'Редактируемая таблица Markdown',
    'tableNode.rowActions': 'Действия со строкой {number}',
    'tableNode.columnActions': 'Действия со столбцом {number}',
    'tableNode.addRowBefore': 'Добавить строку перед',
    'tableNode.addRowAfter': 'Добавить строку ниже',
    'tableNode.duplicateRow': 'Дублировать строку',
    'tableNode.moveRowUp': 'Переместить строку вверх',
    'tableNode.moveRowDown': 'Переместить строку вниз',
    'tableNode.deleteRow': 'Удалить строку',
    'tableNode.addColumnBefore': 'Добавить столбец перед',
    'tableNode.addColumnAfter': 'Добавить столбец справа',
    'tableNode.duplicateColumn': 'Дублировать столбец',
    'tableNode.moveColumnLeft': 'Переместить столбец влево',
    'tableNode.moveColumnRight': 'Переместить столбец вправо',
    'tableNode.deleteColumn': 'Удалить столбец',
    'tableNode.alignColumnLeft': 'Выровнять столбец по левому краю',
    'tableNode.alignColumnCenter': 'Выровнять столбец по центру',
    'tableNode.alignColumnRight': 'Выровнять столбец по правому краю',
    'tableNode.sortAscending': 'Сортировать по возрастанию',
    'tableNode.sortDescending': 'Сортировать по убыванию',
    'tableNode.mergeCellsUnavailable': 'Объединение ячеек недоступно',
    'tableNode.splitCellUnavailable': 'Разделение ячейки недоступно',
    'tableNode.backgroundColorUnavailable': 'Цвет фона ячейки недоступен',
    'tableNode.verticalAlignmentUnavailable': 'Вертикальное выравнивание недоступно',
    'tableNode.persistentWidthUnavailable': 'Постоянная ширина недоступна',
    'tableNode.persistentSortUnavailable': 'Постоянная сортировка недоступна',
    'rawNode.unknownInline': 'Неизвестный встроенный исходный текст',
    'rawNode.unknownBlock': 'Исходник неизвестного блока',
    'rawNode.editSource': 'Редактировать исходный текст',
    'rawNode.editUnknownInline': 'Редактировать неизвестный встроенный исходный текст',
    'rawNode.editUnknownBlock': 'Изменить исходник неизвестного блока',
    'chartEditor.kicker': 'Семантический редактор таблицы диаграммы',
    'chartEditor.title': 'Редактировать таблицу диаграммы',
    'chartEditor.type': 'Тип диаграммы',
    'chartEditor.titleLabel': 'Заголовок',
    'chartEditor.series': 'Ряд',
    'chartEditor.column': 'Столбец {number}',
    'chartEditor.cell': 'Строка {row}, ячейка {cell}',
    'chartEditor.livePreview': 'Предпросмотр диаграммы',
    'chartEditor.previewUnavailable': 'Предпросмотр диаграммы недоступен: {message}',
    'chartEditor.discardTitle': 'Отменить изменения таблицы диаграммы?',
    'chartEditor.unchanged': 'Документ не изменён.',
    'codeEditor.kicker': 'Редактор исходного кода',
    'codeEditor.title': 'Блок кода',
    'codeEditor.source': 'Исходный код',
    'codeEditor.language': 'Язык',
    'codeEditor.discardTitle': 'Отменить изменения локального исходного кода?',
    'codeEditor.dirtyExplanation': 'В этом черновике есть неприменённые изменения.',
    'draftEditor.kicker': 'Семантический редактор',
    'draftEditor.discardTitle': 'Отменить несохранённый черновик?',
    'draftEditor.unchangedExplanation': 'Документ не изменён. Продолжите редактирование или отмените этот отдельный черновик.',
    'drawio.dialogLabel': 'Редактор диаграмм draw.io',
    'drawio.kicker': 'Управляемая интеграция',
    'drawio.title': 'Диаграмма draw.io',
    'drawio.cancelLabel': 'Отменить редактирование draw.io',
    'drawio.iframeTitle': 'Мост draw.io W-Editor',
    'drawio.status.loading': 'Загрузка защищённого моста draw.io…',
    'drawio.status.connecting': 'Подключение к локальному редактору draw.io…',
    'drawio.status.ready': 'Редактор диаграмм готов',
    'drawio.status.saving': 'Рендеринг и применение диаграммы…',
    'drawio.status.unavailable': 'Ресурсы draw.io или CSP не загрузились. Закройте диалог и повторите попытку.',
    'media.kicker': 'Медиа',
    'media.heading': '{kind}',
    'media.name': 'Название',
    'media.url': 'URL',
    'media.localFile': 'Или выберите локальный файл: {kind}',
    'media.uploading': 'Загрузка через настроенный адаптер…',
    'media.uploadReady': '{mediaType} · {size} байт · URL готов',
    'media.nameRequired': 'Название ресурса обязательно.',
    'media.nameInvalid': 'Название ресурса не может содержать закрывающую скобку или перенос строки.',
    'media.urlRequired': 'URL ресурса обязателен.',
    'media.urlUnsupported': 'URL ресурса должен быть абсолютным адресом HTTP или HTTPS.',
    'media.urlCredentials': 'URL ресурса не должен содержать учётные данные.',
    'media.uploadCancelled': 'Загрузка отменена. Документ не изменён.',
    'media.uploadFailed': 'Ошибка загрузки. Документ не изменён.',
    'media.kind.audio': 'аудио',
    'media.kind.file': 'Файл',
    'media.kind.image': 'Изображение',
    'image.width': 'Ширина',
    'image.height': 'Высота',
    'image.lockAspectRatio': 'Сохранять пропорции',
    'image.resetSize': 'Исходный размер',
    'image.edit': 'Изменить изображение',
    'image.dimensions': 'Размер изображения',

    'media.kind.pdf': 'PDF',
    'media.kind.video': 'видео',
    'media.kind.word': 'документ Word',
  }),
} satisfies Record<UiLocale, Record<UiMessageKey, string>>)

const PARAMETER_PATTERN = /\{([A-Za-z][A-Za-z0-9_]*)\}/gu

export function translateUi(locale: UiLocale, key: UiMessageKey, params?: UiMessageParams): string {
  return UI_MESSAGES[locale][key].replace(PARAMETER_PATTERN, (_match, name: string) => {
    if (params === undefined || !Object.hasOwn(params, name)) {
      throw new RangeError(`Missing localization parameter: ${name}`)
    }
    return String(params[name])
  })
}

export function createUiLocalizationStore(initialLocale: UiLocale = 'zh'): UiLocalizationStore {
  let locale = initialLocale
  const listeners = new Set<(nextLocale: UiLocale) => void>()

  return Object.freeze({
    get locale(): UiLocale {
      return locale
    },
    setLocale(nextLocale: UiLocale): void {
      if (nextLocale === locale) return
      locale = nextLocale
      for (const listener of Object.freeze([...listeners])) listener(locale)
    },
    subscribe(listener: (nextLocale: UiLocale) => void): () => void {
      listeners.add(listener)
      return () => listeners.delete(listener)
    },
    t(key: UiMessageKey, params?: UiMessageParams): string {
      return translateUi(locale, key, params)
    },
  })
}
