export type DesktopLocale = 'zh' | 'en' | 'ru'

const EN_MESSAGES = {
  aboutUpdates: 'About & Updates',
  automaticUpdatesDisabled: 'Automatic download and replacement are disabled.',
  cancel: 'Cancel',
  checking: 'Checking…',
  chooseDataRoot: 'Choose a Data Root',
  chooseFolder: 'Choose folder…',
  close: 'Close',
  closeGuard: 'W-Editor will finish composition and synchronization before closing. Choose what to keep.',
  confirmPermanentDeletion: 'Confirm permanent deletion',
  dataAndStorage: 'Data & Storage',
  dataMigration: 'Data migration',
  dataRoot: 'Data Root',
  dataRootNotSelected: 'Data Root not selected',
  deleteDurableQuestion: 'Delete the displayed durable Data Root and all Library history, assets and backups?',
  deleteDurableRoot: 'Delete durable root…',
  desktopLibraryTools: 'Desktop Library tools',
  desktopQuickActions: 'Desktop quick actions',
  documentStatus: 'Document status',
  draft: 'Draft',
  errorNone: 'No errors',
  exportAndClose: 'Export and close',
  exportSaveTitle: 'Save exported file',
  firstUseFolderTitle: 'Choose the W-Editor Data Root parent folder',
  folderPickerFailed: 'The folder picker could not be opened.',
  imported: 'Imported',
  keepAllData: 'Keep all data',
  keepDraft: 'Keep draft',
  library: 'Library',
  libraryArticle: 'Library article',
  lineSpacing: 'Line spacing',
  loadingSettings: 'Loading saved settings…',
  localLibrary: 'Local Library',
  manualUpdates: 'Updates are installed manually.',
  moveDataRoot: 'Move Data Root',
  moveGuard: 'W-Editor will finish composition and synchronization before moving the Library. Choose what to keep first.',
  moveLibrary: 'Move Library',
  migrationFolderTitle: 'Choose the new Library parent folder',
  moveToParentFolder: 'Move to parent folder',
  noRecentActivity: 'No recent activity.',
  parentFolder: 'Parent folder',
  preferences: 'Preferences',
  protectedClose: 'Protected close',
  reader: 'Reader',
  reading: 'Reading…',
  recentArticles: 'Recent articles and imports',
  refreshStatus: 'Refresh status',
  reloadSettings: 'Reload settings',
  reviewUninstallData: 'Review uninstall data',
  save: 'Save',
  saveAndClose: 'Save and close',
  saveAndMove: 'Save and move',
  settings: 'Settings',
  settingsDescription: 'Manage data migration and release information.',
  setupDescription: 'W-Editor stores the Library, versions, recovery drafts and backups only in this managed root.',
  state: 'State',
  sync: 'Sync',
  theme: 'Theme',
  unsignedPackage: 'This test package is unsigned and is not a formal release.',
  uninstallDataOptions: 'Uninstall data options',
  uninstallPreview: 'Preview the managed root before choosing a cleanup scope.',
  unsavedChanges: 'Unsaved changes',
  useThisFolder: 'Use this folder',
  version: 'Version',
  working: 'Working…',
  clearTmpOnly: 'Clear tmp only',
  valueAbyss: 'Abyss',
  valueBlue: 'Blue',
  valueClean: 'clean',
  valueCompact: 'Compact',
  valueDark: 'Dark',
  valueDefault: 'Default',
  valueDirty: 'dirty',
  valueDouble: 'Double',
  valueFailed: 'failed',
  valueGray: 'Gray',
  valueGreen: 'Green',
  valueIdle: 'idle',
  valueLoading: 'loading',
  valueNormal: 'Normal',
  valuePending: 'pending',
  valueReadOnly: 'read only',
  valueReady: 'ready',
  valueRed: 'Red',
  valueSaved: 'saved',
  valueSaving: 'saving',
  valueSingle: 'Single',
  valueStandard: 'Standard',
  valueSynchronized: 'synchronized',
  valueUnavailable: 'unavailable',
  valueUnconfigured: 'not configured',
  valueViolet: 'Violet',
} as const

export type DesktopMessageKey = keyof typeof EN_MESSAGES

const ZH_MESSAGES = {
  aboutUpdates: '关于与更新',
  automaticUpdatesDisabled: '已禁用自动下载和替换。',
  cancel: '取消',
  checking: '正在检查…',
  chooseDataRoot: '选择数据根目录',
  chooseFolder: '选择文件夹…',
  close: '关闭',
  closeGuard: 'W-Editor 将在关闭前完成输入与同步。请选择要保留的内容。',
  confirmPermanentDeletion: '确认永久删除',
  dataAndStorage: '数据与存储',
  dataMigration: '数据迁移',
  dataRoot: '数据根目录',
  dataRootNotSelected: '尚未选择数据根目录',
  deleteDurableQuestion: '是否删除所示数据根目录以及其中全部文章库历史、资源和备份？',
  deleteDurableRoot: '删除持久数据根目录…',
  desktopLibraryTools: '桌面文章库工具',
  desktopQuickActions: '桌面快捷操作',
  documentStatus: '文档状态',
  draft: '草稿',
  errorNone: '无错误',
  exportAndClose: '导出并关闭',
  exportSaveTitle: '保存导出文件',
  firstUseFolderTitle: '选择 W-Editor 数据根目录的父文件夹',
  folderPickerFailed: '无法打开文件夹选择窗口。',
  imported: '已导入',
  keepAllData: '保留全部数据',
  keepDraft: '保留草稿',
  library: '文章库',
  libraryArticle: '文章库文章',
  lineSpacing: '行间距',
  loadingSettings: '正在读取已保存设置…',
  localLibrary: '本地文章库',
  manualUpdates: '更新需手动安装。',
  moveDataRoot: '迁移数据根目录',
  moveGuard: 'W-Editor 将在迁移文章库前完成输入与同步。请先选择要保留的内容。',
  moveLibrary: '迁移文章库',
  migrationFolderTitle: '选择新的文章库父文件夹',
  moveToParentFolder: '迁移到父文件夹',
  noRecentActivity: '暂无最近活动。',
  parentFolder: '父文件夹',
  preferences: '偏好设置',
  protectedClose: '受保护的关闭',
  reader: '阅读',
  reading: '正在读取…',
  recentArticles: '最近文章与导入',
  refreshStatus: '刷新状态',
  reloadSettings: '重新读取设置',
  reviewUninstallData: '检查卸载数据',
  save: '保存',
  saveAndClose: '保存并关闭',
  saveAndMove: '保存并迁移',
  settings: '设置',
  settingsDescription: '管理数据迁移和版本信息。',
  setupDescription: 'W-Editor 只在此受管目录中保存文章库、版本、恢复草稿和备份。',
  state: '状态',
  sync: '同步',
  theme: '主题',
  unsignedPackage: '此测试包未签名，不是正式版本。',
  uninstallDataOptions: '卸载数据选项',
  uninstallPreview: '选择清理范围前，请先检查受管数据根目录。',
  unsavedChanges: '未保存的更改',
  useThisFolder: '使用此文件夹',
  version: '版本',
  working: '正在处理…',
  clearTmpOnly: '仅清理临时文件',
  valueAbyss: '深海',
  valueBlue: '清幽',
  valueClean: '干净',
  valueCompact: '紧凑',
  valueDark: '暗黑',
  valueDefault: '默认',
  valueDirty: '有未保存更改',
  valueDouble: '双倍',
  valueFailed: '失败',
  valueGray: '沉稳',
  valueGreen: '清新',
  valueIdle: '空闲',
  valueLoading: '正在加载',
  valueNormal: '标准',
  valuePending: '待保存',
  valueReadOnly: '只读',
  valueReady: '就绪',
  valueRed: '热情',
  valueSaved: '已保存',
  valueSaving: '正在保存',
  valueSingle: '单倍',
  valueStandard: '标准',
  valueSynchronized: '已同步',
  valueUnavailable: '不可用',
  valueUnconfigured: '未配置',
  valueViolet: '淡雅',
} satisfies Record<DesktopMessageKey, string>

const RU_MESSAGES = {
  aboutUpdates: 'О программе и обновления',
  automaticUpdatesDisabled: 'Автоматическая загрузка и замена отключены.',
  cancel: 'Отмена',
  checking: 'Проверка…',
  chooseDataRoot: 'Выберите папку данных',
  chooseFolder: 'Выбрать папку…',
  close: 'Закрыть',
  closeGuard: 'W-Editor завершит ввод и синхронизацию перед закрытием. Выберите, что сохранить.',
  confirmPermanentDeletion: 'Подтвердить окончательное удаление',
  dataAndStorage: 'Данные и хранилище',
  dataMigration: 'Перенос данных',
  dataRoot: 'Папка данных',
  dataRootNotSelected: 'Папка данных не выбрана',
  deleteDurableQuestion: 'Удалить показанную папку данных вместе со всей историей, ресурсами и резервными копиями?',
  deleteDurableRoot: 'Удалить постоянные данные…',
  desktopLibraryTools: 'Инструменты библиотеки Desktop',
  desktopQuickActions: 'Быстрые действия Desktop',
  documentStatus: 'Состояние документа',
  draft: 'Черновик',
  errorNone: 'Ошибок нет',
  exportAndClose: 'Экспортировать и закрыть',
  exportSaveTitle: 'Сохранить экспортированный файл',
  firstUseFolderTitle: 'Выберите родительскую папку данных W-Editor',
  folderPickerFailed: 'Не удалось открыть окно выбора папки.',
  imported: 'Импортировано',
  keepAllData: 'Сохранить все данные',
  keepDraft: 'Сохранить черновик',
  library: 'Библиотека',
  libraryArticle: 'Статья библиотеки',
  lineSpacing: 'Межстрочный интервал',
  loadingSettings: 'Загрузка сохранённых настроек…',
  localLibrary: 'Локальная библиотека',
  manualUpdates: 'Обновления устанавливаются вручную.',
  moveDataRoot: 'Перенос папки данных',
  moveGuard: 'W-Editor завершит ввод и синхронизацию перед переносом библиотеки. Сначала выберите, что сохранить.',
  moveLibrary: 'Перенести библиотеку',
  migrationFolderTitle: 'Выберите новую родительскую папку библиотеки',
  moveToParentFolder: 'Перенести в родительскую папку',
  noRecentActivity: 'Недавних действий нет.',
  parentFolder: 'Родительская папка',
  preferences: 'Параметры',
  protectedClose: 'Защищённое закрытие',
  reader: 'Чтение',
  reading: 'Чтение…',
  recentArticles: 'Недавние статьи и импорт',
  refreshStatus: 'Обновить состояние',
  reloadSettings: 'Перезагрузить настройки',
  reviewUninstallData: 'Проверить данные удаления',
  save: 'Сохранение',
  saveAndClose: 'Сохранить и закрыть',
  saveAndMove: 'Сохранить и перенести',
  settings: 'Настройки',
  settingsDescription: 'Перенос данных и сведения о версии.',
  setupDescription: 'W-Editor хранит библиотеку, версии, черновики восстановления и резервные копии только в этой управляемой папке.',
  state: 'Состояние',
  sync: 'Синхронизация',
  theme: 'Тема',
  unsignedPackage: 'Этот тестовый пакет не подписан и не является официальным выпуском.',
  uninstallDataOptions: 'Параметры удаления данных',
  uninstallPreview: 'Проверьте управляемую папку перед выбором объёма очистки.',
  unsavedChanges: 'Несохранённые изменения',
  useThisFolder: 'Использовать эту папку',
  version: 'Версия',
  working: 'Выполняется…',
  clearTmpOnly: 'Очистить только временные файлы',
  valueAbyss: 'Бездна',
  valueBlue: 'Синяя',
  valueClean: 'чисто',
  valueCompact: 'Компактный',
  valueDark: 'Тёмная',
  valueDefault: 'По умолчанию',
  valueDirty: 'есть изменения',
  valueDouble: 'Двойной',
  valueFailed: 'ошибка',
  valueGray: 'Серая',
  valueGreen: 'Зелёная',
  valueIdle: 'ожидание',
  valueLoading: 'загрузка',
  valueNormal: 'Обычный',
  valuePending: 'ожидает сохранения',
  valueReadOnly: 'только чтение',
  valueReady: 'готово',
  valueRed: 'Красная',
  valueSaved: 'сохранено',
  valueSaving: 'сохранение',
  valueSingle: 'Одинарный',
  valueStandard: 'Стандартный',
  valueSynchronized: 'синхронизировано',
  valueUnavailable: 'недоступно',
  valueUnconfigured: 'не настроено',
  valueViolet: 'Фиолетовая',
} satisfies Record<DesktopMessageKey, string>

const MESSAGES = Object.freeze({
  en: Object.freeze(EN_MESSAGES),
  ru: Object.freeze(RU_MESSAGES),
  zh: Object.freeze(ZH_MESSAGES),
}) satisfies Record<DesktopLocale, Readonly<Record<DesktopMessageKey, string>>>

const VALUE_KEYS: Readonly<Record<string, DesktopMessageKey>> = Object.freeze({
  abyss: 'valueAbyss',
  blue: 'valueBlue',
  clean: 'valueClean',
  compact: 'valueCompact',
  dark: 'valueDark',
  default: 'valueDefault',
  dirty: 'valueDirty',
  double: 'valueDouble',
  failed: 'valueFailed',
  gray: 'valueGray',
  green: 'valueGreen',
  idle: 'valueIdle',
  loading: 'valueLoading',
  normal: 'valueNormal',
  pending: 'valuePending',
  read_only: 'valueReadOnly',
  ready: 'valueReady',
  red: 'valueRed',
  saved: 'valueSaved',
  saving: 'valueSaving',
  single: 'valueSingle',
  standard: 'valueStandard',
  synchronized: 'valueSynchronized',
  unavailable: 'valueUnavailable',
  unconfigured: 'valueUnconfigured',
  violet: 'valueViolet',
})

export function desktopText(locale: DesktopLocale, key: DesktopMessageKey): string {
  return MESSAGES[locale][key]
}

export function desktopValue(locale: DesktopLocale, value: unknown): string {
  const normalized = String(value ?? '')
  const key = VALUE_KEYS[normalized]
  return key === undefined ? normalized : desktopText(locale, key)
}
