// Generated by scripts/generate-release-version-sources.mjs from release/versions.json. Do not edit.
export const RELEASE_VERSIONS = Object.freeze({
  webApiVersion: '1.0.0',
  webSchemaVersion: '1.0.0',
  hostContractsVersion: '1.0.0',
  minimumHostAdapterVersion: '1.0.0',
} as const)
